Repository facebook/create-react-app, pull requests merged in 2018-11, with the labels that each got.

#5658 Update making-a-progressive-web-app.md
  docusaurus/docs/making-a-progressive-web-app.md
Labels: CLA Signed, tag: documentation

#5659 Add support for decorators
  packages/babel-preset-react-app/create.js
  packages/babel-preset-react-app/package.json
  test/fixtures/typescript/src/App.ts
  test/fixtures/typescript/tsconfig.json
Labels: CLA Signed, tag: bug fix, tag: enhancement

#4709 Expose `reportRuntimeError`
  packages/react-error-overlay/src/index.js
  packages/react-error-overlay/src/listenToRuntimeErrors.js
Labels: CLA Signed, tag: internal

#5685 update envinfo to 5.11.1
  packages/create-react-app/package.json
Labels: CLA Signed, tag: bug fix

#5670 Fix public folder documentation link
  docusaurus/docs/using-the-public-folder.md
Labels: CLA Signed, tag: documentation

#5710 Updated the link to firebase hosting
  docusaurus/docs/deployment.md
Labels: CLA Signed, tag: documentation

#5721 Version bump postcss-preset-env to latest
  packages/react-scripts/package.json
Labels: CLA Signed, tag: bug fix

#5727 Fix typo
  packages/babel-preset-react-app/README.md
  packages/eslint-config-react-app/README.md
  packages/react-error-overlay/README.md
  packages/react-scripts/fixtures/kitchensink/README.md
Labels: CLA Signed, tag: documentation

#5722 Merge webpack configuration
  package.json
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/config/webpackDevServer.config.js
  packages/react-scripts/scripts/build.js
  packages/react-scripts/scripts/start.js
Labels: CLA Signed, tag: internal

#5730 Suggest Encore when not building a SPA with Symfony
  README.md
Labels: CLA Signed, tag: documentation

#5759 Add PR welcoming badge
  README.md
Labels: CLA Signed, tag: documentation

#5779 docs: Change story book command to `sb init`
  docusaurus/docs/developing-components-in-isolation.md
Labels: CLA Signed, tag: documentation

#5789 Don't polyfill fetch for Node -- additional files
  packages/react-app-polyfill/ie11.js
  packages/react-app-polyfill/ie9.js
Labels: CLA Signed, tag: bug fix

#5788 docs: Simplify installing Storybook with npx
  docusaurus/docs/developing-components-in-isolation.md
Labels: CLA Signed, tag: documentation

#5814 extra polyfills must be included manually, fixes #5795
  packages/react-app-polyfill/README.md
Labels: CLA Signed, tag: documentation

#5849 React native repository updated in README.md
  README.md
Labels: CLA Signed, tag: documentation

#5573 fix named-asset-import plugin to work with export-as syntax
  packages/babel-plugin-named-asset-import/index.js
  packages/babel-plugin-named-asset-import/index.test.js
Labels: CLA Signed, tag: bug fix

#5487 Add allowESModules option to babel-preset-react-app
  packages/babel-preset-react-app/create.js
Labels: CLA Signed, tag: internal, tag: new feature

#5451 fix: add `sideEffects: false` to react-error-overlay
  packages/react-error-overlay/package.json
Labels: CLA Signed, tag: internal

#5783 Fix TypeScript decorator support
  packages/babel-preset-react-app/create.js
  test/fixtures/typescript/src/App.test.ts
  test/fixtures/typescript/src/App.ts
Labels: CLA Signed, tag: bug fix

#5546 Add the latest stable node version
  .travis.yml
Labels: CLA Signed, tag: internal

#5879 fix: make typescriptformatter support 0.5 of fork checker
  packages/react-dev-utils/typescriptFormatter.js
Labels: CLA Signed, tag: internal

#5883 Fix link to page about running tests
  docusaurus/docs/getting-started.md
Labels: CLA Signed, tag: documentation

#5858 Some Grammar fixes
  README.md
Labels: tag: documentation

#5839 Run prettier on HTML files
  package.json
  packages/react-scripts/fixtures/kitchensink/public/index.html
  packages/react-scripts/template-typescript/public/index.html
  packages/react-scripts/template/public/index.html
  test/fixtures/__shared__/template/public/index.html
Labels: CLA Signed, tag: internal

#5698 Add support for setupTests.ts
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/scripts/utils/createJestConfig.js
Labels: CLA Signed, tag: enhancement

#5905 Disable copy to clipboard in cra --info
  packages/create-react-app/createReactApp.js
Labels: CLA Signed, tag: bug fix

#5808 Add placeholders to template README for bit.ly links.
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#5907 Update README.md with updated link about PWAs
  README.md
Labels: CLA Signed

#5823 Add default values to `file_ext` note
  docusaurus/docs/adding-a-sass-stylesheet.md
Labels: CLA Signed, tag: documentation

#5927 Correct some comments
  packages/react-dev-utils/WebpackDevServerUtils.js
Labels: CLA Signed, tag: internal

#5930 Add netlify.toml to prepare for deploy to netlify #5807
  netlify.toml
Labels: CLA Signed
