Repository facebook/create-react-app, pull requests merged in 2018-12, with the labels that each got.

#5954 Add pre-eject message about new features in v2
  packages/react-scripts/scripts/eject.js
Labels: CLA Signed, tag: documentation

#5959 Suggest a different default for speed reasons
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
Labels: CLA Signed, tag: internal

#5917 Add SASS_PATH instructions to Sass stylesheet docs
  docusaurus/docs/adding-a-sass-stylesheet.md
Labels: CLA Signed, tag: documentation

#5919 Docs: update localStorage mock in “Running Tests”
  docusaurus/docs/running-tests.md
Labels: CLA Signed, tag: documentation

#5974 Improve advice in verifyPackageTree.js
  packages/react-scripts/scripts/utils/verifyPackageTree.js
Labels: CLA Signed

#5985 Use https for linked images to fix mixed content warnings
  docusaurus/docs/running-tests.md
Labels: CLA Signed, tag: documentation

#5912 Update links to docs in all package README files
  .github/ISSUE_TEMPLATE.md
  README.md
  packages/babel-preset-react-app/README.md
  packages/create-react-app/README.md
  packages/eslint-config-react-app/README.md
  packages/react-dev-utils/README.md
  packages/react-scripts/README.md
  packages/react-scripts/bin/react-scripts.js
Labels: CLA Signed, tag: documentation

#5988 Added extension to .eslintrc
  .eslintrc.json
Labels: CLA Signed, tag: internal

#5990 Updated docs re: .eslintrc
  docusaurus/docs/setting-up-your-editor.md
  packages/eslint-config-react-app/README.md
Labels: CLA Signed

#5900 Add production build section to docs
  docusaurus/docs/available-scripts.md
  docusaurus/docs/code-splitting.md
  docusaurus/docs/deployment.md
  docusaurus/docs/production-build.md
  docusaurus/docs/running-tests.md
  docusaurus/website/i18n/en.json
  docusaurus/website/sidebars.json
Labels: CLA Signed, tag: documentation

#6000 Make links to docs consistent in README
  README.md
Labels: tag: documentation

#6015 Add example command to create typed project
  docusaurus/docs/adding-typescript.md
Labels: CLA Signed

#5978 add webp support for typescript
  packages/react-scripts/lib/react-app.d.ts
Labels: CLA Signed, tag: internal

#6009 Correct markdown to avoid comment
  docusaurus/docs/proxying-api-requests-in-development.md
Labels: CLA Signed, tag: documentation

#6061 Fix control comment of CSS Grid prefixing
  docusaurus/docs/post-processing-css.md
Labels: CLA Signed, tag: documentation

#6084 Remove outdated docs for setting up eslint in editor
  docusaurus/docs/setting-up-your-editor.md
Labels: CLA Signed

#5631 Generalize the adding bootstrap documentation
  docusaurus/docs/adding-bootstrap.md
Labels: CLA Signed, tag: documentation

#6036 Fix comment typo
  packages/react-scripts/config/webpack.config.js
Labels: tag: documentation
