Repository facebook/create-react-app, pull requests merged in 2018-10, with the labels that each got.

#5182 Strip flow syntax before any other transform
  packages/babel-preset-react-app/create.js
  packages/babel-preset-react-app/package.json
Labels: CLA Signed, tag: bug fix

#5111 Updates to README to reflect Workbox usage.
  README.md
  packages/react-scripts/template/README.md
Labels: tag: documentation

#5184 Still emit runtime chunk
  packages/react-dev-utils/InlineChunkHtmlPlugin.js
Labels: CLA Signed, tag: bug fix

#5192 Add license file to all packages
  packages/babel-plugin-named-asset-import/LICENSE
  packages/babel-preset-react-app/LICENSE
  packages/confusing-browser-globals/LICENSE
  packages/create-react-app/LICENSE
  packages/eslint-config-react-app/LICENSE
  packages/react-app-polyfill/LICENSE
  packages/react-dev-utils/LICENSE
  packages/react-error-overlay/LICENSE
  packages/react-scripts/LICENSE
Labels: CLA Signed, tag: internal

#5193 Fix typo in 'Configuring the Proxy Manually'
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#5196 Format SVG React snapshots as <svg> tag with props
  packages/react-scripts/config/jest/fileTransform.js
Labels: CLA Signed, tag: bug fix

#5197 Treat .css and .sass/.scss as side effectful
  packages/react-scripts/config/webpack.config.prod.js
Labels: CLA Signed, tag: bug fix

#5136 Plug'n'Play support
  .travis.yml
  appveyor.yml
  packages/create-react-app/createReactApp.js
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/package.json
  packages/react-scripts/scripts/init.js
  packages/react-scripts/scripts/utils/createJestConfig.js
  tasks/e2e-installs.sh
Labels: CLA Signed

#5203 Fix IE 11 compatibility
  packages/react-error-overlay/src/utils/mapper.js
Labels: CLA Signed, tag: bug fix

#5205 Disable react/no-deprecated rule
  packages/eslint-config-react-app/index.js
Labels: CLA Signed, tag: internal, tag: underlying tools

#5211 Adds instructions to README on how to customize Bootstrap with Sass
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#5212 Don't crash npm test when hg/git are missing
  packages/react-scripts/scripts/test.js
Labels: CLA Signed, tag: bug fix

#5202 Feed correct line number to gvim on launch
  packages/react-dev-utils/launchEditor.js
Labels: CLA Signed

#5214 Fix absolute paths on eject
  packages/react-scripts/scripts/utils/createJestConfig.js
Labels: CLA Signed, tag: bug fix

#5218 Support globalSetup and globalTeardown Jest options
  packages/react-scripts/scripts/utils/createJestConfig.js
Labels: CLA Signed, tag: new feature

#5219 Add changelog for v2-final
  CHANGELOG-1.x.md
  CHANGELOG.md
Labels: CLA Signed, tag: documentation

#5227 Initial setup of Docusaurus
  website/README.md
  website/blog/2016-03-11-blog-post.md
  website/blog/2017-04-10-blog-post-two.md
  website/blog/2017-09-25-testing-rss.md
  website/blog/2017-09-26-adding-rss.md
  website/blog/2017-10-24-new-version-1.0.0.md
  website/core/Footer.js
  website/i18n/en.json
  website/package.json
  website/pages/en/help.js
  website/pages/en/index.js
  website/pages/en/users.js
  website/sidebars.json
  website/siteConfig.js
  website/static/css/custom.css
  website/static/img/docusaurus.svg
  website/static/img/favicon.png
  website/static/img/favicon/favicon.ico
  website/static/img/oss_logo.png
  website/yarn.lock
Labels: CLA Signed

#5233 DOCS: Add Relay example
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#5239 5238 removing blog from Docusaurus
  website/README.md
  website/blog/2016-03-11-blog-post.md
  website/blog/2017-04-10-blog-post-two.md
  website/blog/2017-09-25-testing-rss.md
  website/blog/2017-09-26-adding-rss.md
  website/blog/2017-10-24-new-version-1.0.0.md
  website/core/Footer.js
  website/i18n/en.json
  website/siteConfig.js
Labels: CLA Signed, tag: documentation

#5246 Fix GENERATE_SOURCEMAP env not working for css sourcemap
  packages/react-scripts/config/webpack.config.prod.js
Labels: CLA Signed, tag: bug fix

#5244 Update favicon and OpenGraph images
  website/siteConfig.js
  website/static/img/favicon.png
  website/static/img/favicon/favicon.ico
  website/static/img/logo-og.png
Labels: CLA Signed, tag: documentation

#5226 Fix usage of http-proxy-middleware
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#5249 Set the color palette to something a bit more React-y
  website/i18n/en.json
  website/siteConfig.js
Labels: CLA Signed, tag: documentation

#5252 Revert change to http-proxy-middleware docs
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#5254 Update README links for CSS modules and SASS
  README.md
Labels: CLA Signed, tag: documentation

#5258 Add `.mjs` support back to webpack (it has native ESM support)
  .travis.yml
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
Labels: CLA Signed, tag: bug fix

#5263 Add browser test for graphql
  fixtures/browser/graphql-with-mjs/__snapshots__/index.test.js.snap
  fixtures/browser/graphql-with-mjs/index.test.js
  fixtures/browser/graphql-with-mjs/package.json
  fixtures/browser/graphql-with-mjs/public/index.html
  fixtures/browser/graphql-with-mjs/src/App.js
  fixtures/browser/graphql-with-mjs/src/index.js
  fixtures/browser/jest.config.js
  fixtures/browser/setupBrowserTests.js
  fixtures/smoke/graphql-with-mjs/index.test.js
  fixtures/smoke/graphql-with-mjs/src/App.js
  fixtures/utils.js
  package.json
  tasks/e2e-behavior.sh
Labels: CLA Signed, tag: internal

#5269 Adds a version check when using --use-pnp
  packages/create-react-app/createReactApp.js
Labels: CLA Signed

#5270 Caches the Yarn resolution for faster installs
  CONTRIBUTING.md
  package.json
  packages/create-react-app/createReactApp.js
  packages/create-react-app/package.json
  packages/create-react-app/yarn.lock.cached
  tasks/compile-lockfile.js
  tasks/publish.sh
Labels: CLA Signed

#5228 removed create-react-app-parcel link
  README.md
Labels: CLA Signed

#5278 Disable Symbol typeof transform
  packages/babel-preset-react-app/create.js
  packages/babel-preset-react-app/dependencies.js
Labels: CLA Signed, tag: bug fix

#5281 Disable Terser inline 3 option
  packages/react-scripts/config/webpack.config.prod.js
Labels: CLA Signed, tag: bug fix

#5245 5238 set up basic docs structure
  docusaurus/docs/README.md
  docusaurus/docs/getting-started.md
  docusaurus/docs/user-guide.md
  docusaurus/website/README.md
  docusaurus/website/core/Footer.js
  docusaurus/website/i18n/en.json
  docusaurus/website/package.json
  docusaurus/website/pages/en/index.js
  docusaurus/website/sidebars.json
  docusaurus/website/siteConfig.js
  docusaurus/website/static/css/custom.css
  docusaurus/website/static/img/docusaurus.svg
  docusaurus/website/static/img/favicon/favicon.ico
  docusaurus/website/static/img/logo-og.png
  docusaurus/website/static/img/oss_logo.png
  docusaurus/website/yarn.lock
  website/sidebars.json
Labels: CLA Signed

#5251 Add SoMe links to documentation
  docusaurus/website/core/Footer.js
  docusaurus/website/siteConfig.js
Labels: CLA Signed, tag: documentation

#5290 add react-testing-library documentation/examples (#4679)
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#5296 Adding documentation about git init
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#5301 avoid TypeError on when registering service workers without config
  packages/react-scripts/template/src/serviceWorker.js
Labels: CLA Signed, tag: bug fix

#5317 Remove unused require for getCacheIdentifier after ejecting
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
Labels: CLA Signed, tag: internal

#5327 Updated the URL in index.html
  packages/react-scripts/template/public/index.html
Labels: CLA Signed, tag: documentation

#5326 README link fixes
  README.md
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#5330 Update eslint-plugin-jsx-a11y version
  packages/react-scripts/package.json
Labels: CLA Signed, tag: enhancement

#5335 Fix file size report after build (#5333)
  packages/react-dev-utils/FileSizeReporter.js
Labels: CLA Signed, tag: bug fix

#5337 Fix typo
  CHANGELOG.md
Labels: CLA Signed, tag: documentation

#5341 Add callouts and logo
  docusaurus/website/i18n/en.json
  docusaurus/website/pages/en/index.js
  docusaurus/website/siteConfig.js
  docusaurus/website/static/css/custom.css
  docusaurus/website/static/img/logo.svg
Labels: CLA Signed

#5344 Add some headings to the getting started section
  docusaurus/docs/getting-started.md
Labels: CLA Signed, tag: documentation

#5354 Add environment variable to optionaly disable inlining of chunks
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: enhancement

#5362 Fix CI: non-semver compliant Yarn versions
  packages/create-react-app/createReactApp.js
Labels: CLA Signed, tag: internal

#5371 Update path to serviceWorker.js in graphical folder structure
  README.md
  docusaurus/docs/getting-started.md
Labels: CLA Signed, tag: documentation

#5357 Potpourri
  docusaurus/docs/adding-a-css-modules-stylesheet.md
  docusaurus/docs/adding-a-router.md
  docusaurus/docs/adding-a-sass-stylesheet.md
  docusaurus/docs/adding-a-stylesheet.md
  docusaurus/docs/adding-custom-environment-variables.md
  docusaurus/docs/adding-images-fonts-and-files.md
  docusaurus/docs/alternatives-to-ejecting.md
  docusaurus/docs/analyzing-the-bundle-size.md
  docusaurus/docs/available-scripts.md
  docusaurus/docs/changing-the-page-title.md
  docusaurus/docs/debugging-in-the-editor.md
  docusaurus/docs/debugging-tests.md
  docusaurus/docs/deployment.md
  docusaurus/docs/developing-components-in-isolation.md
  docusaurus/docs/documentation-intro.md
  docusaurus/docs/fetching-data-with-ajax-requests.md
  docusaurus/docs/folder-structure.md
  docusaurus/docs/formatting-code-automatically.md
  docusaurus/docs/generating-dynamic-meta-tags-on-the-server.md
  docusaurus/docs/getting-started.md
  docusaurus/docs/importing-a-component.md
  docusaurus/docs/injecting-data-from-the-server-into-the-page.md
  docusaurus/docs/installing-a-dependency.md
  docusaurus/docs/integrating-with-an-api-backend.md
  docusaurus/docs/lint-output-in-the-editor.md
  docusaurus/docs/making-a-progressive-web-app.md
  docusaurus/docs/pre-rendering-into-static-html-files.md
  docusaurus/docs/proxying-api-requests-in-development.md
  docusaurus/docs/publishing-components-to-npm.md
  docusaurus/docs/running-tests.md
  docusaurus/docs/sending-feedback.md
  docusaurus/docs/setting-up-your-editor.md
  docusaurus/docs/something-missing.md
  docusaurus/docs/supported-browsers.md
  docusaurus/docs/supported-language-features.md
  docusaurus/docs/syntax-highlighting-in-the-editor.md
  docusaurus/docs/title-and-meta-tags.md
  docusaurus/docs/updating-to-new-releases.md
  docusaurus/docs/using-https-in-development.md
  docusaurus/docs/using-the-public-folder.md
  docusaurus/website/core/Footer.js
  docusaurus/website/i18n/en.json
  docusaurus/website/sidebars.json
  docusaurus/website/siteConfig.js
  docusaurus/website/static/css/custom.css
Labels: CLA Signed

#5398 Add some front page content
  docusaurus/website/pages/en/index.js
  docusaurus/website/static/css/custom.css
  docusaurus/website/static/img/update.png
Labels: CLA Signed

#5416 Fix eslint config docs.
  packages/eslint-config-react-app/README.md
Labels: CLA Signed, tag: documentation

#5374 Add the new SVGs feature from the template README to the root README
  README.md
Labels: CLA Signed, tag: documentation

#5431 Fix click-to-open on Windows
  packages/react-dev-utils/launchEditor.js
Labels: CLA Signed, tag: bug fix

#5394 Correct instructions for HTTPS and PowerShell
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#5350 Update eslint-config-react-app/README to reflect new dependency versions
  packages/eslint-config-react-app/README.md
Labels: CLA Signed, tag: documentation

#5321 Added note on update to .flowconfig for .scss imports
  packages/react-scripts/template/README.md
Labels: tag: documentation

#5449 Remove dot from the end of the link to fix it when using from GitHub
  packages/react-scripts/template/src/serviceWorker.js
Labels: CLA Signed, tag: documentation

#5475 Fix typo
  packages/react-scripts/scripts/build.js
Labels: CLA Signed

#5493 Fixed typo in getting-started
  docusaurus/docs/getting-started.md
Labels: CLA Signed

#5494 Fix typo
  docusaurus/docs/developing-components-in-isolation.md
  docusaurus/docs/integrating-with-an-api-backend.md
Labels: CLA Signed, tag: documentation

#4837 TypeScript support using Babel 7
  README.md
  docusaurus/docs/adding-typescript.md
  docusaurus/docs/running-tests.md
  docusaurus/docs/setting-up-your-editor.md
  docusaurus/docs/supported-browsers-features.md
  docusaurus/website/i18n/en.json
  docusaurus/website/sidebars.json
  packages/babel-preset-react-app/README.md
  packages/babel-preset-react-app/create.js
  packages/babel-preset-react-app/package.json
  packages/react-scripts/config/paths.js
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/scripts/test.js
  packages/react-scripts/scripts/utils/createJestConfig.js
  packages/react-scripts/template/src/loaders.d.ts
  packages/react-scripts/template/src/serviceWorker.d.ts
  test/fixtures/typescript/.disable-pnp
  test/fixtures/typescript/index.test.js
  test/fixtures/typescript/package.json
  test/fixtures/typescript/src/App.test.ts
  test/fixtures/typescript/src/App.ts
Labels: CLA Signed, tag: new feature

#5499 Fix title on Safari
  docusaurus/website/static/css/custom.css
Labels: CLA Signed, tag: documentation

#5492 Add "edit" feature to Docusaurus pages
  docusaurus/website/siteConfig.js
Labels: CLA Signed, tag: documentation

#5515 Always type check TypeScript when being used
  docusaurus/docs/adding-typescript.md
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: enhancement

#5524 Validate tsconfig when using TypeScript
  docusaurus/docs/adding-typescript.md
  packages/react-scripts/config/react-app.d.ts
  packages/react-scripts/scripts/test.js
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
Labels: tag: enhancement

#5529 Add TypeScript error formatting
  packages/react-dev-utils/package.json
  packages/react-dev-utils/typescriptFormatter.js
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
Labels: tag: enhancement

#5531 Enable TypeScript json module resolver
  packages/react-scripts/config/react-app.d.ts
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
Labels: tag: enhancement

#5533 Simplified TypeScript steps
  docusaurus/docs/adding-typescript.md
Labels: tag: documentation

#5537 Respect tsconfig.json extends when validating config
  packages/react-dev-utils/immer.js
  packages/react-dev-utils/package.json
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
Labels: CLA Signed, tag: bug fix

#5469 Avoid pushing .pnp folder to git
  packages/react-scripts/template/gitignore
Labels: CLA Signed, tag: internal

#5549 Automatically setup TypeScript when detected
  packages/react-dev-utils/globby.js
  packages/react-dev-utils/package.json
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
  test/fixtures/typescript/package.json
Labels: CLA Signed, tag: bug fix

#5551 Add Algolia search bar to Docusaurus
  docusaurus/website/siteConfig.js
Labels: CLA Signed, tag: documentation

#5559 Change import syntax from typescript declaration
  packages/react-scripts/config/react-app.d.ts
Labels: CLA Signed, tag: internal

#5588 Update TypeScript template
  packages/react-scripts/template-typescript/src/App.tsx
Labels: CLA Signed

#5586 Fixing the code splitting links in the ESLint output
  packages/eslint-config-react-app/index.js
Labels: CLA Signed, tag: internal

#5589 Update react-app.d.ts
  packages/react-scripts/config/react-app.d.ts
Labels: CLA Signed, tag: bug fix

#5593 Refine how TypeScript types are handled
  docusaurus/docs/adding-typescript.md
  packages/create-react-app/createReactApp.js
  packages/react-scripts/config/paths.js
  packages/react-scripts/config/react-app.d.ts
  packages/react-scripts/package.json
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
Labels: CLA Signed, tag: enhancement

#5607 Turn on certain TypeScript options
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/package.json
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
Labels: CLA Signed, tag: internal

#5609 Remove unsupported options
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
Labels: CLA Signed, issue: typescript, tag: bug fix

#5614 Ignore json files from TypeScript type checking
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
Labels: CLA Signed, tag: bug fix

#5552 Fixing Internal Links
  docusaurus/docs/adding-a-css-modules-stylesheet.md
  docusaurus/docs/adding-a-router.md
  docusaurus/docs/adding-a-sass-stylesheet.md
  docusaurus/docs/adding-custom-environment-variables.md
  docusaurus/docs/advanced-configuration.md
  docusaurus/docs/alternatives-to-ejecting.md
  docusaurus/docs/available-scripts.md
  docusaurus/docs/deployment.md
  docusaurus/docs/making-a-progressive-web-app.md
  docusaurus/docs/proxying-api-requests-in-development.md
  docusaurus/docs/setting-up-your-editor.md
  docusaurus/docs/title-and-meta-tags.md
  docusaurus/docs/troubleshooting.md
  docusaurus/docs/using-https-in-development.md
  docusaurus/docs/using-the-public-folder.md
Labels: CLA Signed, tag: documentation

#5611 Remove react-scripts type reference on eject
  packages/react-scripts/config/paths.js
  packages/react-scripts/lib/react-app.d.ts
  packages/react-scripts/package.json
  packages/react-scripts/scripts/eject.js
  tasks/e2e-installs.sh
Labels: CLA Signed, issue: typescript, tag: bug fix

#5629 Add link to cra-ts migration guide
  docusaurus/docs/adding-typescript.md
Labels: CLA Signed, tag: documentation

#5635 Update minimum node version to 8.10 in README
  README.md
Labels: CLA Signed, tag: documentation

#5621 fix 'Duplicate string index signature' in ProcessEnv
  packages/react-scripts/lib/react-app.d.ts
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
Labels: CLA Signed, tag: bug fix

#5651 Make serviceWorker config argument optional in typescript
  packages/react-scripts/template-typescript/src/serviceWorker.ts
Labels: CLA Signed, tag: internal

#5575 add tests for named-asset-imports plugin
  packages/babel-plugin-named-asset-import/index.test.js
  packages/babel-plugin-named-asset-import/package.json
  tasks/e2e-simple.sh
Labels: CLA Signed, tag: internal
