Repository facebook/create-react-app, pull requests merged in 2018-09, with the labels that each got.

#4955 Update webpack-dev-server 3.1.5 → 3.1.7
  packages/react-scripts/package.json
Labels: CLA Signed

#4846 Update jest version
  packages/confusing-browser-globals/package.json
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed

#5026 Switch from uglifyjs to terser
  packages/react-dev-utils/printBuildError.js
  packages/react-error-overlay/package.json
  packages/react-error-overlay/webpack.config.iframe.js
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: bug fix, tag: internal

#5030 Disable webpack chunk coalescing
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
Labels: CLA Signed, tag: bug fix, tag: enhancement

#5031 Upgrade `html-webpack-plugin` to fix tests
  packages/react-dev-utils/InterpolateHtmlPlugin.js
  packages/react-dev-utils/README.md
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: internal

#3924 Updates to reflect service worker registration being opt-in.
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/template/README.md
Labels: tag: documentation

#5032 Upgrade `react-scripts` dependencies
  .yarnrc
  packages/confusing-browser-globals/package.json
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: internal

#5033 Lock babel configuration back to IE 9 support (ES5)
  packages/babel-preset-react-app/create.js
Labels: CLA Signed, tag: internal

#5042 Upgrade to Babel 7 stable
  packages/babel-plugin-named-asset-import/package.json
  packages/babel-preset-react-app/create.js
  packages/babel-preset-react-app/package.json
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: internal

#5043 Always lint with latest React version
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
Labels: CLA Signed, tag: bug fix, tag: internal

#5035 Remove paywalled tutorial link for Storybook
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#5047 Allow dynamic import proposal in node_modules
  packages/babel-preset-react-app/dependencies.js
Labels: CLA Signed, tag: new feature

#4930 Switch from cheap-module-source-map eval-source-map
  packages/react-dev-utils/evalSourceMapMiddleware.js
  packages/react-dev-utils/package.json
  packages/react-error-overlay/src/utils/mapper.js
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpackDevServer.config.js
Labels: CLA Signed, tag: enhancement

#4550 Jest 23 and tests
  packages/react-scripts/fixtures/kitchensink/.template.dependencies.json
  packages/react-scripts/fixtures/kitchensink/README.md
  packages/react-scripts/fixtures/kitchensink/integration/env.test.js
  packages/react-scripts/fixtures/kitchensink/integration/initDOM.js
  packages/react-scripts/fixtures/kitchensink/integration/syntax.test.js
  packages/react-scripts/fixtures/kitchensink/integration/webpack.test.js
  packages/react-scripts/fixtures/kitchensink/jest.integration.config.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/assets/scss-styles.scss
  packages/react-scripts/template/README.md
  tasks/e2e-kitchensink-eject.sh
  tasks/e2e-kitchensink.sh
Labels: CLA Signed

#5050 Eslint 5.6
  package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: internal

#5051 Adjust ESLint configuration for v5
  packages/eslint-config-react-app/index.js
Labels: CLA Signed, tag: internal

#4774 [internal] Use Yarn cache for travis
  .travis.yml
Labels: CLA Signed, tag: internal

#5052 Add Babel config sourceType: 'unambiguous' for dependencies
  packages/babel-preset-react-app/dependencies.js
Labels: CLA Signed, tag: bug fix

#5053 Normalize babel caching across the board
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
Labels: CLA Signed, tag: internal

#5054 Ensure Babel files get purged on upgrades
  packages/react-dev-utils/getCacheIdentifier.js
  packages/react-dev-utils/package.json
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
Labels: CLA Signed, tag: internal

#5055 Cache identifier follow up
  packages/react-dev-utils/README.md
  packages/react-dev-utils/getCacheIdentifier.js
Labels: CLA Signed

#4891 Move favicon.ico <link> to accommodate Chrome
  packages/react-scripts/template/public/index.html
Labels: CLA Signed, tag: internal

#5059 Switch back to cheap-module-source-map
  packages/react-scripts/config/webpack.config.dev.js
Labels: CLA Signed, tag: internal

#5062 Upgrade svgr to v2 and disable Prettier & SVGO
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: internal

#5064 fix minor typo in troubleshooting github pages
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#5065 (Micro) Optimize webpack rebuild speed
  packages/react-dev-utils/FileSizeReporter.js
  packages/react-dev-utils/WebpackDevServerUtils.js
  packages/react-scripts/scripts/build.js
Labels: CLA Signed, tag: enhancement

#5072 Drop support for advanced proxy
  packages/react-dev-utils/WebpackDevServerUtils.js
Labels: CLA Signed, tag: breaking change

#5070 Integrating with an API Backend: add API Platform
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#5074 Change default test environment to jsdom
  package.json
  packages/react-scripts/scripts/init.js
  packages/react-scripts/scripts/test.js
  packages/react-scripts/scripts/utils/createJestConfig.js
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: breaking change

#5076 Revert "Add loader for .graphql files (#3909)"
  packages/react-scripts/config/jest/graphqlTransform.js
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/fixtures/kitchensink/integration/webpack.test.js
  packages/react-scripts/fixtures/kitchensink/src/App.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/GraphQLInclusion.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/GraphQLInclusion.test.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/assets/graphql.graphql
  packages/react-scripts/package.json
  packages/react-scripts/scripts/utils/createJestConfig.js
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: internal

#5077 small typo fix
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#5071 Update usage advice of husky to 1.0
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#5078 Prevent the cache of files using Babel Macros
  .eslintrc
  packages/babel-preset-react-app/loader.js
  packages/babel-preset-react-app/overrides.js
  packages/babel-preset-react-app/package.json
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
Labels: CLA Signed, tag: bug fix

#4716 add postcss-preset-env, remove autoprefixer
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: enhancement

#5090 Drop IE 11 support by default
  packages/react-app-polyfill/README.md
  packages/react-app-polyfill/ie11.js
  packages/react-app-polyfill/ie9.js
  packages/react-app-polyfill/jsdom.js
  packages/react-app-polyfill/package.json
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/package.json
  packages/react-scripts/scripts/utils/createJestConfig.js
Labels: CLA Signed, tag: breaking change

#5093 Turn on Babel `helpers`
  packages/babel-preset-react-app/create.js
  packages/babel-preset-react-app/dependencies.js
  packages/babel-preset-react-app/dev.js
  packages/babel-preset-react-app/prod.js
  packages/babel-preset-react-app/test.js
  packages/react-error-overlay/webpack.config.iframe.js
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
  tasks/e2e-kitchensink.sh
Labels: CLA Signed, tag: enhancement

#5098 [internal] remove babelrc dependency for kitchensink test
  packages/react-scripts/fixtures/kitchensink/jest.integration.config.js
  packages/react-scripts/fixtures/kitchensink/jest.transform.js
  tasks/e2e-kitchensink.sh
  tasks/local-test.sh
Labels: CLA Signed, tag: internal

#3833 Revert " Remove CSS modules docs"
  packages/react-scripts/template/README.md
Labels: CLA Signed

#4551 Update targeted IE version in documentation
  CONTRIBUTING.md
Labels: CLA Signed, tag: documentation

#5109 Prevent Babel config overridden
  packages/react-error-overlay/webpack.config.iframe.js
  packages/react-scripts/config/jest/babelTransform.js
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
Labels: CLA Signed, tag: bug fix

#5110 Add dynamic import transformer for dependencies in test env
  packages/babel-preset-react-app/dependencies.js
Labels: CLA Signed, tag: bug fix

#4630 Eliminate regenerator from preset-react-app plugins
  packages/babel-preset-react-app/create.js
Labels: CLA Signed, tag: bug fix

#5102 Fix Troubleshooting link
  README.md
Labels: CLA Signed, tag: documentation

#5119 Clean up @babel/plugin-transform-regenerator
  packages/babel-preset-react-app/dependencies.js
  packages/babel-preset-react-app/package.json
Labels: CLA Signed, tag: internal

#5131 Output CSS sourcemaps in separate file
  packages/react-scripts/config/webpack.config.prod.js
Labels: CLA Signed, tag: bug fix

#5134 Lists loader-utils in the dependencies
  packages/react-dev-utils/package.json
Labels: CLA Signed, tag: bug fix

#4169 Workbox service worker
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: enhancement

#5137 Fix displaying third party webpack plugins errors
  packages/react-dev-utils/formatWebpackMessages.js
Labels: CLA Signed, tag: bug fix

#5142 Remove runtime alias hack
  packages/babel-preset-react-app/create.js
  packages/babel-preset-react-app/dependencies.js
  packages/babel-preset-react-app/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: bug fix

#5146 Add behavior e2e tests
  .eslintignore
  .travis.yml
  fixtures/behavior/builds-with-multiple-runtimes/package.json
  fixtures/behavior/builds-with-multiple-runtimes/src/index.js
  package.json
  tasks/e2e-behavior.sh
  tasks/test-behavior.js
Labels: CLA Signed, tag: internal

#5143 Switch back to babel-loader
  packages/babel-preset-react-app/loader.js
  packages/babel-preset-react-app/overrides.js
  packages/babel-preset-react-app/package.json
  packages/babel-preset-react-app/webpack-overrides.js
  packages/react-error-overlay/package.json
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: internal

#5150 Run behavioral smoke tests with Jest, add output tests
  fixtures/behavior/builds-with-multiple-runtimes/package.json
  fixtures/output/jest.config.js
  fixtures/output/setupOutputTests.js
  fixtures/output/webpack-message-formatting/__snapshots__/index.test.js.snap
  fixtures/output/webpack-message-formatting/index.test.js
  fixtures/output/webpack-message-formatting/package.json
  fixtures/output/webpack-message-formatting/public/index.html
  fixtures/output/webpack-message-formatting/src/AppBabel.js
  fixtures/output/webpack-message-formatting/src/AppCss.css
  fixtures/output/webpack-message-formatting/src/AppCss.js
  fixtures/output/webpack-message-formatting/src/AppLintError.js
  fixtures/output/webpack-message-formatting/src/AppLintWarning.js
  fixtures/output/webpack-message-formatting/src/AppMissingPackage.js
  fixtures/output/webpack-message-formatting/src/AppUnknownExport.js
  fixtures/output/webpack-message-formatting/src/FooExport.js
  fixtures/output/webpack-message-formatting/src/index.js
  fixtures/smoke/boostrap-sass/index.test.js
  fixtures/smoke/boostrap-sass/package.json
  fixtures/smoke/boostrap-sass/public/index.html
  fixtures/smoke/boostrap-sass/src/index.js
  fixtures/smoke/boostrap-sass/src/index.sass
  fixtures/smoke/builds-with-multiple-runtimes/index.test.js
  fixtures/smoke/builds-with-multiple-runtimes/package.json
  fixtures/smoke/builds-with-multiple-runtimes/public/index.html
  fixtures/smoke/builds-with-multiple-runtimes/src/index.js
  fixtures/smoke/jest.config.js
  fixtures/smoke/setupSmokeTests.js
  fixtures/utils.js
  package.json
  packages/react-dev-utils/__tests__/__snapshots__/formatWebpackMessages.test.js.snap
  packages/react-dev-utils/__tests__/formatWebpackMessages.test.js
  tasks/e2e-behavior.sh
  tasks/e2e-installs.sh
  tasks/e2e-kitchensink-eject.sh
  tasks/e2e-kitchensink.sh
  tasks/e2e-simple.sh
  tasks/test-behavior.js
Labels: CLA Signed, tag: internal

#5151 Toggle `mjs` files to `javascript/auto` type
  fixtures/smoke/graphql-with-mjs/index.test.js
  fixtures/smoke/graphql-with-mjs/package.json
  fixtures/smoke/graphql-with-mjs/public/index.html
  fixtures/smoke/graphql-with-mjs/src/App.js
  fixtures/smoke/graphql-with-mjs/src/index.js
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
Labels: CLA Signed, tag: bug fix

#5157 Forwards args through thread-loader
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
Labels: CLA Signed

#5163 Correctly lookup assets when using a relative build directory
  fixtures/smoke/relative-paths/index.test.js
  fixtures/smoke/relative-paths/package.json
  fixtures/smoke/relative-paths/public/index.html
  fixtures/smoke/relative-paths/src/index.css
  fixtures/smoke/relative-paths/src/index.js
  fixtures/smoke/relative-paths/src/logo.svg
  package.json
  packages/react-scripts/config/webpack.config.prod.js
Labels: CLA Signed, tag: bug fix

#5169 Add additional troubleshooting for Github Pages
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#5170 Remove thread-loader
  fixtures/output/webpack-message-formatting/index.test.js
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: internal

#5174 💅 Polish webpack message output
  .travis.yml
  fixtures/output/webpack-message-formatting/__snapshots__/index.test.js.snap
  fixtures/output/webpack-message-formatting/index.test.js
  fixtures/output/webpack-message-formatting/package.json
  fixtures/output/webpack-message-formatting/src/AppAliasUnknownExport.js
  fixtures/output/webpack-message-formatting/src/AppIncorrectCase.js
  fixtures/output/webpack-message-formatting/src/AppNoDefault.js
  fixtures/output/webpack-message-formatting/src/AppOutOfScopeImport.js
  fixtures/output/webpack-message-formatting/src/AppSass.js
  fixtures/output/webpack-message-formatting/src/AppSass.scss
  fixtures/output/webpack-message-formatting/src/AppUnknownFile.js
  fixtures/output/webpack-message-formatting/src/Export5.js
  fixtures/output/webpack-message-formatting/src/ExportNoDefault.js
  fixtures/smoke/boostrap-sass/package.json
  fixtures/smoke/builds-with-multiple-runtimes/package.json
  fixtures/smoke/graphql-with-mjs/package.json
  fixtures/smoke/relative-paths/package.json
  fixtures/utils.js
  packages/react-dev-utils/ModuleNotFoundPlugin.js
  packages/react-dev-utils/ModuleScopePlugin.js
  packages/react-dev-utils/eslintFormatter.js
  packages/react-dev-utils/formatWebpackMessages.js
  packages/react-dev-utils/package.json
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/scripts/build.js
  tasks/e2e-behavior.sh
Labels: CLA Signed, tag: enhancement

#5180 Fetch Workbox from CDN
  packages/react-scripts/config/webpack.config.prod.js
Labels: CLA Signed, tag: internal
