Repository facebook/create-react-app, pull requests merged in 2018-02, with the labels that each got.

#3997 Use yarn when running inside yarn workspace.
  packages/create-react-app/createReactApp.js
  packages/create-react-app/package.json
  packages/react-dev-utils/package.json
  packages/react-dev-utils/workspaceUtils.js
  packages/react-scripts/config/paths.js
  packages/react-scripts/package.json
  packages/react-scripts/scripts/build.js
  packages/react-scripts/scripts/eject.js
  packages/react-scripts/scripts/start.js
Labels: CLA Signed, tag: bug fix

#4009 Update dotenv to 5.0.0
  packages/react-scripts/package.json
Labels: CLA Signed

#4001 Add support for new yarn workspaces config format
  packages/react-dev-utils/workspaceUtils.js
Labels: CLA Signed, tag: enhancement

#4016 (chore): Alphabetize and clean files-array in react-dev-utils package.json
  packages/react-dev-utils/package.json
Labels: CLA Signed, tag: internal
