Repository facebook/create-react-app, pull requests merged in 2018-04, with the labels that each got.

#4234 [next] Revert to use ecma 5 in uglifyOptions
  packages/react-scripts/config/webpack.config.prod.js
Labels: CLA Signed, tag: bug fix

#4239 Fix typo in comment and be clearer about `ecma` settings in uglifyjs options
  packages/react-scripts/config/webpack.config.prod.js
Labels: CLA Signed

#4236 use the lastest url of gitignore file
  packages/react-scripts/template/gitignore
Labels: CLA Signed, tag: documentation

#4247 Work around Jest environment resolving bug
  packages/react-scripts/package.json
  packages/react-scripts/scripts/test.js
Labels: CLA Signed, tag: bug fix

#4250 hotfix/update detect-port-alt
  packages/react-dev-utils/package.json
Labels: CLA Signed, tag: bug fix

#4253 Upgrade Babel to `beta.44`
  packages/babel-plugin-named-asset-import/package.json
  packages/babel-preset-react-app/package.json
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: internal

#4248 Enable loose mode for `class-properties`
  packages/babel-preset-react-app/index.js
Labels: tag: bug fix

#4192 Update CSS Modules localIndetName
  packages/react-dev-utils/README.md
  packages/react-dev-utils/getCSSModuleLocalIdent.js
  packages/react-dev-utils/package.json
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/fixtures/kitchensink/integration/webpack.test.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/CssModulesInclusion.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/assets/index.module.css
  packages/react-scripts/package.json
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: enhancement

#4303 Fixed link to document describing CSS import
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#4117 Document multiple build environments via `env-cmd` #4071
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#4298 Added learnstorybook.com to Storybook links
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#4286 Fix some typos in README.md
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#4195 Sass loader
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/fixtures/kitchensink/.template.dependencies.json
  packages/react-scripts/fixtures/kitchensink/integration/webpack.test.js
  packages/react-scripts/fixtures/kitchensink/src/App.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/SassInclusion.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/SassInclusion.test.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/SassModulesInclusion.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/SassModulesInclusion.test.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/ScssInclusion.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/ScssInclusion.test.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/ScssModulesInclusion.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/ScssModulesInclusion.test.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/assets/sass-styles.module.sass
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/assets/sass-styles.sass
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/assets/scss-styles.module.scss
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/assets/scss-styles.scss
  packages/react-scripts/package.json
Labels: CLA Signed, tag: new feature

#4323 Fix typo in e2e-simple.sh comment
  tasks/e2e-simple.sh
Labels: CLA Signed, tag: documentation

#4331 Bump `fsevents`.
  packages/react-scripts/package.json
Labels: CLA Signed, tag: internal

#4294 documentation: added License to the README.md
  README.md
Labels: CLA Signed, tag: documentation

#4362 Bumped jest version to 22.4.1
  packages/confusing-browser-globals/package.json
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: enhancement

#4361 [hot]fix broken css module support in prod
  packages/react-scripts/config/webpack.config.prod.js
Labels: CLA Signed, issue: bug

#4350 Support package distribution tags
  packages/create-react-app/createReactApp.js
  tasks/e2e-installs.sh
Labels: CLA Signed, tag: new feature

#4376 Update sass-loader (#4363)
  packages/react-scripts/fixtures/kitchensink/.template.dependencies.json
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/assets/scss-styles.scss
  packages/react-scripts/package.json
Labels: CLA Signed, tag: bug fix

#4375 fix: update envinfo + implementation, update issue_template
  .github/ISSUE_TEMPLATE.md
  packages/create-react-app/createReactApp.js
  packages/create-react-app/package.json
Labels: CLA Signed, tag: enhancement
