Repository facebook/create-react-app, pull requests merged in 2018-03, with the labels that each got.

#4107 docs: use node_js 8 in example travis.yml
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#4089 Fix a typo in packages/react-scripts/template/README.md
  packages/react-scripts/template/README.md
Labels: CLA Signed

#4114 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: CLA Signed, tag: documentation

#4134 fix: Minor typos
  CONTRIBUTING.md
Labels: CLA Signed, tag: documentation

#4160 Remove ref to non free resource
  packages/react-scripts/template/README.md
Labels: CLA Signed

#4187 Change no-unused-vars 'args' from none to all to show warning on dest…
  packages/eslint-config-react-app/index.js
Labels: CLA Signed

#4193 Minor fixes to CI
  packages/react-error-overlay/src/effects/proxyConsole.js
  packages/react-error-overlay/src/utils/getStackFrames.js
  tasks/e2e-installs.sh
  tasks/e2e-kitchensink.sh
  tasks/e2e-monorepos.sh
  tasks/e2e-simple.sh
Labels: CLA Signed, tag: internal

#4164 Fix typos in example monorepo documentation.
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#4085 BUG MITIGATION: .mjs should not resolve before .js files
  packages/react-scripts/scripts/utils/createJestConfig.js
Labels: CLA Signed, tag: bug fix

#4197 Add troubleshooting for Github Pages
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#4138 Allow ModuleScopePlugin accecpts an array as its appSrc
  packages/react-dev-utils/ModuleScopePlugin.js
  packages/react-dev-utils/README.md
Labels: CLA Signed, tag: internal

#4048 Add ESLint check for incorrect propTypes usage (#3840)
  packages/eslint-config-react-app/index.js
  packages/eslint-config-react-app/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: enhancement

#4211 Revert lint-related changes made in #4193
  packages/react-error-overlay/src/effects/proxyConsole.js
  packages/react-error-overlay/src/utils/getStackFrames.js
Labels: CLA Signed, tag: internal

#4015 add `create-react-app --help` info for local file path `--scripts-version` support
  packages/create-react-app/createReactApp.js
Labels: CLA Signed, tag: documentation

#4174 Yarn workspace transpilation verification.
  packages/react-scripts/fixtures/monorepos/packages/comp1/index.js
Labels: CLA Signed, tag: internal

#4024 Fix floating caret position incorrect while scrolling overlay
  packages/react-error-overlay/src/components/CodeBlock.js
Labels: CLA Signed, tag: bug fix
