Repository facebook/create-react-app, pull requests merged in 2018-06, with the labels that each got.

#4546 Update file tree view
  README.md
Labels: CLA Signed, tag: documentation

#3945 Allow bundles to be analyzed with Webpack-specific tools
  packages/react-scripts/package.json
  packages/react-scripts/scripts/build.js
  packages/react-scripts/template/README.md
Labels: CLA Signed

#4566 Move whitespace comment closer to where it applies
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#4562 Configured the thread-loader to keeping workers alive in development mode
  packages/react-scripts/config/webpack.config.dev.js
Labels: CLA Signed

#4582 Added thread-loader tweak for application code entry-point
  packages/react-scripts/config/webpack.config.dev.js
Labels: CLA Signed, tag: enhancement

#4623 Use yarn build command in predeploy script if using yarn
  packages/react-dev-utils/printHostingInstructions.js
Labels: CLA Signed, tag: enhancement

#4626 [internal] Fix node 10 test issue
  tasks/e2e-installs.sh
  tasks/e2e-kitchensink.sh
  tasks/e2e-monorepos.sh
  tasks/e2e-simple.sh
  tasks/verdaccio.yaml
Labels: CLA Signed, tag: internal

#4638 Add instructions on alternative methods of app creation
  README.md
Labels: CLA Signed, tag: documentation

#4668 Add modes to our Babel preset (1.x)
  packages/babel-preset-react-app/create.js
  packages/babel-preset-react-app/dev.js
  packages/babel-preset-react-app/index.js
  packages/babel-preset-react-app/package.json
  packages/babel-preset-react-app/prod.js
  packages/babel-preset-react-app/test.js
Labels: CLA Signed

#4677 Support scoped package names for scripts-version option in create-react-app cli
  packages/create-react-app/createReactApp.js
Labels: CLA Signed, tag: bug fix

#4679 add react-testing-library documentation/examples
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation
