Repository facebook/create-react-app, pull requests merged in 2018-07, with the labels that each got.

#4741 remove extra dot on devtool link comment
  packages/react-scripts/config/webpack.config.dev.js
Labels: CLA Signed, tag: documentation

#4738 Fix typo
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#4776 Bump babel-loader to fix npm warning
  packages/react-scripts/package.json
Labels: CLA Signed, tag: internal

#4706 Only use safe options when packing CSS assets
  packages/react-scripts/config/webpack.config.prod.js
Labels: CLA Signed, tag: bug fix

#4825 Update support info for service workers
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation
