Repository facebook/create-react-app, pull requests merged in 2018-05, with the labels that each got.

#4391 Update getCSSModuleLocalIdent to support Sass
  packages/react-dev-utils/getCSSModuleLocalIdent.js
  packages/react-scripts/fixtures/kitchensink/integration/webpack.test.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/SassModulesInclusion.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/ScssModulesInclusion.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/assets/index.module.sass
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/assets/index.module.scss
Labels: CLA Signed, tag: bug fix

#4424 ensureSlash: Fix accidental string-to-NaN coercion
  packages/react-scripts/config/paths.js
Labels: CLA Signed, tag: bug fix

#4420 Update the thread loader test in formatWebpackMessages
  packages/react-dev-utils/formatWebpackMessages.js
Labels: CLA Signed, tag: bug fix

#4432 Update babel-plugin-macros to fix a bug
  packages/babel-preset-react-app/package.json
Labels: CLA Signed, tag: enhancement

#4449 add create-react-app-parcel to Alternatives section in README
  README.md
Labels: CLA Signed, tag: documentation

#4461 Update svgr
  packages/react-scripts/package.json
Labels: CLA Signed, tag: enhancement

#4419 Map (s?css|sass) modules to identity-obj-proxy in jest
  packages/react-scripts/scripts/utils/createJestConfig.js
Labels: CLA Signed, tag: bug fix

#4309 Fix typo to word bootstrapped in condition to check for old version o…
  packages/create-react-app/createReactApp.js
Labels: CLA Signed, tag: documentation

#4205 Chokidar Updates
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#4497 [Read Me template patch] Warn about #871 until it's actually fixed.
  packages/react-scripts/template/README.md
Labels: CLA Signed

#4435 Update paths.js, rename shadow path variable
  packages/react-scripts/config/paths.js
Labels: CLA Signed

#4504 webpack 4 scope hoisting
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/fixtures/kitchensink/.template.dependencies.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: enhancement

#4470 Adjust browser defaults
  packages/react-dev-utils/browsersHelper.js
Labels: tag: enhancement

#3929 Remove trailing spaces from copyright
  tasks/cra.js
Labels: CLA Signed

#4014 enable manifest plugin on dev
  packages/react-scripts/config/webpack.config.dev.js
Labels: CLA Signed
