Repository facebook/create-react-app, pull requests merged in 2019-07, with the labels that each got.

#7289 fix(eject): guard against empty key before access
  packages/react-scripts/scripts/eject.js
Labels: CLA Signed

#7317 Fix typo
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: CLA Signed, tag: documentation

#7182 Fix issue #7181
  README.md
Labels: CLA Signed, tag: documentation

#7355 Fix typos
  CHANGELOG-1.x.md
  azure-pipelines.yml
  packages/react-error-overlay/src/utils/unmapper.js
  packages/react-scripts/config/webpack.config.js
  tasks/e2e-installs.sh
Labels: CLA Signed, tag: documentation, tag: internal

#7118 Append title element to SVG component via title prop
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/proposal.md
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: enhancement, tag: underlying tools

#7374 docs(svg): add tip for title props accessibility
  docusaurus/docs/adding-images-fonts-and-files.md
Labels: CLA Signed, tag: documentation

#7036 Add ESLint extend support to eslint-loader
  docusaurus/docs/advanced-configuration.md
  docusaurus/docs/setting-up-your-editor.md
  packages/eslint-config-react-app/index.js
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/scripts/eject.js
Labels: CLA Signed, tag: new feature, tag: underlying tools

#7230 jsx-no-duplicate-props ignore case fix
  packages/eslint-config-react-app/index.js
Labels: CLA Signed, tag: bug fix

#7372 proposal dynamic import are stage 4
  docusaurus/docs/code-splitting.md
Labels: CLA Signed, tag: documentation

#7385 Attempt at fixing CI issue on windows
  tasks/local-registry.sh
Labels: CLA Signed, tag: internal

#7378 Update url-loader to 2.0.1
  packages/react-scripts/package.json
Labels: CLA Signed

#7260 Docs: remove an outdated TypeScript-related note
  docusaurus/docs/running-tests.md
Labels: CLA Signed, tag: documentation

#7423 Add question issue template
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/proposal.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: CLA Signed, tag: documentation

#7429 Update deploy instructions in contributing guide
  CONTRIBUTING.md
Labels: CLA Signed

#7433 Add explicit check for --watchAll=false
  packages/react-scripts/scripts/test.js
Labels: CLA Signed, tag: bug fix, tag: internal

#7415 Add ESLint 6 support
  package.json
  packages/eslint-config-react-app/index.js
  packages/eslint-config-react-app/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
  packages/react-scripts/scripts/utils/createJestConfig.js
Labels: CLA Signed, tag: enhancement, tag: underlying tools

#7340 Update testing-library related npm package names in README
  docusaurus/docs/running-tests.md
Labels: CLA Signed, tag: documentation

#7451 Update README for ESLint config
  packages/eslint-config-react-app/README.md
Labels: CLA Signed, tag: documentation
