Repository facebook/create-react-app, pull requests merged in 2019-11, with the labels that each got.

#7921 Add restoreMocks to supported jest config keys
  packages/react-scripts/scripts/utils/createJestConfig.js
Labels: CLA Signed, tag: enhancement

#7932 fix seperators typo
  packages/babel-preset-react-app/create.js
Labels: CLA Signed

#7931 No spinning React logo if `prefers-reduced-motion`
  packages/cra-template/template/src/App.css
Labels: CLA Signed, tag: enhancement

#7792 [Docs]: minor tweak
  README.md
Labels: CLA Signed, tag: documentation

#7944 Make base and TypeScript templates consistent
  packages/cra-template-typescript/template/src/App.css
  packages/cra-template-typescript/template/src/App.test.tsx
Labels: CLA Signed, tag: internal

#7951 Fix CI
  package.json
  packages/babel-preset-react-app/package.json
  packages/cra-template-typescript/template.json
  packages/create-react-app/package.json
  packages/create-react-app/yarn.lock.cached
  packages/react-app-polyfill/package.json
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
  tasks/publish.sh
  test/fixtures/typescript-advanced/package.json
  test/fixtures/typescript-typecheck/package.json
  test/fixtures/typescript/package.json
Labels: CLA Signed, tag: internal

#7438 Add optional chaining and nullish coalescing operators support
  packages/babel-preset-react-app/create.js
  packages/babel-preset-react-app/package.json
Labels: CLA Signed, tag: new feature

#7952 Add tests for optional chaining and null coalescing
  CHANGELOG.md
  packages/react-scripts/fixtures/kitchensink/template/src/App.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/NullishCoalescing.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/NullishCoalescing.test.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/OptionalChaining.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/OptionalChaining.test.js
Labels: CLA Signed, tag: internal

#7956 Upgrade jest-watch-typeahead
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#7936 Fix light background in docusaurus night mode
  docusaurus/website/src/pages/index.js
  docusaurus/website/src/pages/styles.module.css
Labels: CLA Signed

#7972 Add placeholders where old template READMEs used to be
  packages/react-dev-utils/printHostingInstructions.js
  packages/react-scripts/template-typescript/README.md
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#7978 Temporarily disable GitHub Actions
  .github/workflows-disabled/build.yml
  .github/workflows-disabled/lint.yml
Labels: CLA Signed, tag: internal

#7986 Bump dependencies
  package.json
  packages/babel-preset-react-app/package.json
  packages/react-app-polyfill/package.json
  packages/react-dev-utils/package.json
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#7991 Support templates in scoped packages
  packages/create-react-app/createReactApp.js
Labels: CLA Signed

#7995 Add contributors section to readme
  README.md
Labels: CLA Signed, tag: documentation

#7844 added e2e test for checking typescript template with unsupported node
  azure-pipelines.yml
  packages/create-react-app/createReactApp.js
  tasks/e2e-typescript-unsupported-node.sh
Labels: CLA Signed, tag: internal

#7999 Unpin dependencies in react-app-polyfill
  packages/react-app-polyfill/package.json
Labels: CLA Signed, tag: underlying tools

#7989 Add scripts support to templates
  packages/react-scripts/scripts/init.js
Labels: CLA Signed, tag: enhancement

#8003 Use @typescript-eslint/no-unused-expressions to support optional chaining
  packages/eslint-config-react-app/index.js
Labels: CLA Signed, tag: internal

#8005 Prefix apple-touch-icon links with PUBLIC_URL
  packages/cra-template-typescript/template/public/index.html
  packages/cra-template/template/public/index.html
Labels: CLA Signed

#7988 Bump webpack-dev-server
  packages/create-react-app/yarn.lock.cached
  packages/react-dev-utils/package.json
  packages/react-dev-utils/webpackHotDevClient.js
  packages/react-scripts/config/webpackDevServer.config.js
  packages/react-scripts/fixtures/kitchensink/template/integration/initDOM.js
  packages/react-scripts/package.json
  tasks/e2e-kitchensink-eject.sh
  tasks/e2e-kitchensink.sh
Labels: CLA Signed, tag: breaking change, tag: underlying tools

#8024 Bump dependencies
  package.json
  packages/babel-preset-react-app/package.json
  packages/cra-template-typescript/template.json
  packages/cra-template/template.json
  packages/create-react-app/package.json
  packages/create-react-app/yarn.lock.cached
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
  tasks/local-test.sh
  test/fixtures/typescript-advanced/src/App.tsx
Labels: CLA Signed, tag: underlying tools

#8029 Re-enable GitHub Actions
  .github/workflows/build.yml
  .github/workflows/lint.yml
Labels: CLA Signed, tag: internal

#8039 Remove no-unexpected-multiline rule
  CHANGELOG.md
  packages/eslint-config-react-app/index.js
Labels: CLA Signed, tag: bug fix

#8038 Add TypeScript peer dependency to react-scripts
  packages/react-scripts/package.json
Labels: tag: internal

#8050 Update template docs
  CHANGELOG.md
  docusaurus/docs/custom-templates.md
  docusaurus/docs/getting-started.md
Labels: CLA Signed, tag: documentation
