Repository facebook/create-react-app, pull requests merged in 2019-01, with the labels that each got.

#6110 Replace deprecated VSCode launch.json variable
  docusaurus/docs/setting-up-your-editor.md
Labels: CLA Signed, tag: documentation

#6067 Correct an error for documentation
  docusaurus/docs/adding-a-css-modules-stylesheet.md
Labels: CLA Signed

#6137 Fix CI and upgrade dependencies
  .travis.yml
  appveyor.yml
  package.json
  packages/babel-preset-react-app/package.json
  packages/react-app-polyfill/package.json
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: internal

#6132 Bump eslint-plugin-react version and update webpack config
  packages/eslint-config-react-app/index.js
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#5060 Enable eval-source-map for firefox
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: enhancement

#6141 Remove extra table cell
  docusaurus/docs/advanced-configuration.md
Labels: CLA Signed, tag: documentation

#6149 update link for difference between proposal stages
  docusaurus/docs/supported-browsers-features.md
Labels: CLA Signed, tag: documentation

#6162 Update react-dev-util globby dependency to v8.0.2
  packages/react-dev-utils/package.json
Labels: CLA Signed, tag: internal

#6157 Add note for global install of CLI
  docusaurus/docs/getting-started.md
Labels: CLA Signed, tag: documentation

#6165 Fix CI builds
  test/fixtures/relative-paths/package.json
Labels: CLA Signed

#6179 Update local-test.sh to return test exit code
  tasks/local-test.sh
Labels: CLA Signed, tag: internal

#5816 Upgrade @svgr/webpack to 4.1.0
  packages/babel-plugin-named-asset-import/index.test.js
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: internal

#6150 dependencies: move chalk to react-dev-utils
  packages/react-dev-utils/chalk.js
  packages/react-dev-utils/package.json
  packages/react-scripts/package.json
  packages/react-scripts/scripts/build.js
  packages/react-scripts/scripts/eject.js
  packages/react-scripts/scripts/init.js
  packages/react-scripts/scripts/start.js
  packages/react-scripts/scripts/utils/createJestConfig.js
  packages/react-scripts/scripts/utils/verifyPackageTree.js
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
Labels: CLA Signed

#6022 TypeScript detection filtering 'node_modules'.
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
  test/fixtures/issue-5947-not-typescript/index.test.js
  test/fixtures/issue-5947-not-typescript/package.json
Labels: CLA Signed

#6095 Changes to steps for publishing GitHub User Page
  docusaurus/docs/deployment.md
Labels: CLA Signed, tag: documentation

#6190 Updating updating-to-new-releases.md for users who installed CRA globally
  docusaurus/docs/updating-to-new-releases.md
Labels: CLA Signed, tag: documentation

#6229 Update `serve` port flag and add example
  docusaurus/docs/deployment.md
Labels: CLA Signed, tag: documentation
