Repository facebook/create-react-app, pull requests merged in 2019-09, with the labels that each got.

#7620 cleanup-after-each is no longer necessary!
  docusaurus/docs/running-tests.md
Labels: CLA Signed, tag: documentation

#7650 Adopt Contributor Covenant
  CODE_OF_CONDUCT.md
  docusaurus/website/core/Footer.js
Labels: CLA Signed, tag: documentation

#7662 Fix build
  package.json
  packages/babel-preset-react-app/package.json
  packages/react-error-overlay/flow/env.js
  packages/react-error-overlay/package.json
  packages/react-error-overlay/src/index.js
  packages/react-error-overlay/src/listenToRuntimeErrors.js
  packages/react-scripts/package.json
  tasks/e2e-simple.sh
Labels: CLA Signed, tag: bug fix

#7633 Disable babel-loader's cacheCompression
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: enhancement

#7459 Update troubleshooting.md
  docusaurus/docs/troubleshooting.md
Labels: CLA Signed, tag: documentation

#7538 Explicitly checking that EXTEND_ESLINT is true
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: bug fix

#7659 Update running-tests.md
  docusaurus/docs/running-tests.md
Labels: CLA Signed, tag: documentation

#7540 Bump version of @typescript-eslint/*
  packages/eslint-config-react-app/README.md
  packages/eslint-config-react-app/index.js
  packages/eslint-config-react-app/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#7531 Upgrade dotenv-expand to fix issues
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#7587 Minor performance improvements
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: enhancement

#7663 Remove --single-quote from prettier examples
  docusaurus/docs/setting-up-your-editor.md
Labels: CLA Signed, tag: documentation

#7526 The variable dotenvFiles is never reassigned - use const instead
  packages/react-scripts/config/env.js
Labels: CLA Signed, tag: internal

#7679 Change runtime chunk name separator from tilde to dash
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: bug fix

#7681 Bump dependencies
  package.json
  packages/babel-plugin-named-asset-import/package.json
  packages/confusing-browser-globals/package.json
  packages/react-app-polyfill/package.json
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/fixtures/kitchensink/.template.dependencies.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#7616 Update deployment.md with another AWS example
  docusaurus/docs/deployment.md
Labels: CLA Signed

#7705 Update runtime chunk name separator in docs
  docusaurus/docs/production-build.md
Labels: CLA Signed, tag: documentation

#7707 Remove 'shortcut' link type before 'icon'
  docusaurus/docs/using-the-public-folder.md
  packages/react-dev-utils/README.md
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/config/webpackDevServer.config.js
  packages/react-scripts/fixtures/kitchensink/integration/env.test.js
  packages/react-scripts/fixtures/kitchensink/public/index.html
  packages/react-scripts/template-typescript/public/index.html
  packages/react-scripts/template/public/index.html
Labels: CLA Signed, tag: internal

#7205 Guard polyfills against window possibly being undefined
  packages/react-app-polyfill/ie11.js
  packages/react-app-polyfill/ie9.js
Labels: CLA Signed, tag: bug fix

#7562 enable .eslintignore again
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: enhancement

#7721 Add "entrypoints" key to asset manifest
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: enhancement

#7731 docs: fix module mapper regex in Flow documentation
  docusaurus/docs/adding-flow.md
Labels: CLA Signed

#7742 set output.globalObject to 'this'
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: enhancement

#7530 only load eslint config when EXTEND_ESLINT environment variable is specified/ do not swallow eslint config errors
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: enhancement

#7601 [Documentation] Updated list of supported Jest config overrides
  docusaurus/docs/running-tests.md
Labels: CLA Signed, tag: documentation

#7740 Update webpack to improve performance
  packages/react-scripts/package.json
Labels: CLA Signed

#7668 Close <br> tags in templates' READMEs
  packages/react-scripts/template-typescript/README.md
  packages/react-scripts/template/README.md
Labels: CLA Signed

#7752 Fix wrong letter casing
  packages/react-scripts/config/jest/fileTransform.js
Labels: CLA Signed

#7757 Documentation typo fix: accessbile→accessible
  docusaurus/docs/adding-images-fonts-and-files.md
Labels: CLA Signed, tag: documentation
