Repository facebook/create-react-app, pull requests merged in 2019-04, with the labels that each got.

#4176 Remove --coverage + --watch workaround for the test command
  packages/react-scripts/scripts/test.js
Labels: CLA Signed, tag: breaking change, tag: internal

#5481 Document .graphql and .gql file loading with graphql.macro
  docusaurus/docs/loading-graphql-files.md
  docusaurus/website/i18n/en.json
  docusaurus/website/sidebars.json
Labels: CLA Signed, tag: documentation

#6082 Add explanation for adding everything as dependencies to docs
  docusaurus/docs/available-scripts.md
Labels: CLA Signed, tag: documentation

#6654 Cleanup Jest config
  package.json
  packages/babel-plugin-named-asset-import/package.json
  packages/confusing-browser-globals/package.json
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/fixtures/kitchensink/.template.dependencies.json
  packages/react-scripts/fixtures/kitchensink/README.md
  packages/react-scripts/fixtures/kitchensink/integration/env.test.js
  packages/react-scripts/fixtures/kitchensink/integration/initDOM.js
  packages/react-scripts/fixtures/kitchensink/integration/syntax.test.js
  packages/react-scripts/fixtures/kitchensink/integration/webpack.test.js
  packages/react-scripts/fixtures/kitchensink/src/App.js
  packages/react-scripts/package.json
  packages/react-scripts/scripts/utils/createJestConfig.js
  tasks/local-test.sh
Labels: CLA Signed, tag: internal

#6757 Add temporary workaround for Babel dependency issues in installs test suite
  tasks/e2e-installs.sh
Labels: tag: internal

#6696 Enable futureEmitAssets in webpack config
  packages/react-scripts/config/webpack.config.js
Labels: tag: enhancement

#6160 Suggests that tsconfig.json is incorrect only when SyntaxError is caught
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
Labels: CLA Signed, tag: enhancement

#6759 Fix unlogged yarn pnp message
  packages/create-react-app/createReactApp.js
Labels: CLA Signed

#6732 fix: terser-webpack-plugin hanging on WSL
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: bug fix

#6746 Replace deprecated SFC with FunctionComponent in react-app.d.ts
  packages/react-scripts/lib/react-app.d.ts
Labels: CLA Signed, tag: enhancement

#6762 Add temporary workaround for Babel dependency issues in kitchensink-eject test suite
  tasks/e2e-kitchensink-eject.sh
Labels: CLA Signed, tag: internal

#6725 Update to workbox-webpack-plugin v4
  packages/react-scripts/package.json
Labels: CLA Signed

#5810 Adds PostCSS Normalize
  docusaurus/docs/adding-css-reset.md
  docusaurus/website/sidebars.json
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: new feature

#6739 Update fork-ts-checker-webpack-plugin out of alpha
  packages/react-dev-utils/package.json
Labels: CLA Signed, tag: underlying tools

#6767 Update dependency versions
  package.json
  packages/babel-preset-react-app/create.js
  packages/babel-preset-react-app/package.json
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#6750 change NODE_ENV and PUBLIC_URL into readonly
  packages/react-scripts/lib/react-app.d.ts
Labels: CLA Signed, tag: breaking change

#6695 Add Render deployment section
  docusaurus/docs/deployment.md
Labels: CLA Signed, tag: documentation

#6772 Update link to React Testing Library docs
  docusaurus/docs/running-tests.md
Labels: CLA Signed, tag: documentation

#6770 Warn when using react-scripts-ts
  packages/create-react-app/createReactApp.js
  packages/create-react-app/package.json
Labels: CLA Signed, tag: enhancement

#6775 Fix code comment typo
  packages/react-scripts/scripts/start.js
Labels: CLA Signed, tag: documentation

#6780 Remove unused babel-loader from babel-preset-react-app
  packages/babel-preset-react-app/package.json
Labels: CLA Signed, tag: underlying tools

#6783 Add SVG support dependency note
  docusaurus/docs/adding-images-fonts-and-files.md
Labels: CLA Signed, tag: documentation

#6786 Clarify production build output files documentation
  docusaurus/docs/production-build.md
Labels: CLA Signed, tag: documentation

#6817 Add link to TypeScript page in Getting Started
  docusaurus/docs/getting-started.md
Labels: CLA Signed, tag: documentation

#6820 Fix docs about minimum React version for SVG component support
  docusaurus/docs/adding-images-fonts-and-files.md
Labels: CLA Signed, tag: documentation

#6801 Copy fix
  docusaurus/docs/adding-bootstrap.md
Labels: CLA Signed, tag: documentation

#6769 Update to core-js@3
  docusaurus/docs/supported-browsers-features.md
  packages/babel-preset-react-app/create.js
  packages/react-app-polyfill/README.md
  packages/react-app-polyfill/ie11.js
  packages/react-app-polyfill/ie9.js
  packages/react-app-polyfill/package.json
  packages/react-app-polyfill/stable.js
Labels: CLA Signed, tag: breaking change, tag: enhancement

#6735 InlineChunkHtmlPlugin works with empty publicPath
  packages/react-dev-utils/InlineChunkHtmlPlugin.js
Labels: CLA Signed, tag: bug fix

#6580 Fix react-scripts peer-deps link local issue
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: internal

#6821 Add custom function to generate asset manifest
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: breaking change, tag: enhancement

#6313 Update testMatch to also be compatible with Jest 24
  packages/react-scripts/scripts/utils/createJestConfig.js
Labels: CLA Signed, tag: internal

#6826 Add directory details to packages/* package.json
  packages/babel-plugin-named-asset-import/package.json
  packages/babel-preset-react-app/package.json
  packages/confusing-browser-globals/package.json
  packages/create-react-app/package.json
  packages/eslint-config-react-app/package.json
  packages/react-app-polyfill/package.json
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: enhancement

#6656 Set baseUrl from jsconfig.json/tsconfig.json
  docusaurus/docs/deployment.md
  docusaurus/docs/getting-started.md
  packages/react-scripts/config/modules.js
  packages/react-scripts/config/paths.js
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/fixtures/kitchensink/integration/config.test.js
  packages/react-scripts/fixtures/kitchensink/integration/env.test.js
  packages/react-scripts/fixtures/kitchensink/jsconfig.json
  packages/react-scripts/fixtures/kitchensink/src/App.js
  packages/react-scripts/fixtures/kitchensink/src/features/config/BaseUrl.js
  packages/react-scripts/fixtures/kitchensink/src/features/config/BaseUrl.test.js
  packages/react-scripts/scripts/build.js
  packages/react-scripts/scripts/start.js
  packages/react-scripts/scripts/utils/createJestConfig.js
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
  tasks/e2e-kitchensink.sh
  tasks/local-test.sh
  test/fixtures/node_path/.disable-pnp
  test/fixtures/node_path/.env
  test/fixtures/node_path/index.test.js
  test/fixtures/node_path/package.json
  test/fixtures/node_path/src/App.js
  test/fixtures/node_path/src/App.test.js
  test/fixtures/node_path/src/absoluteLoad.js
  test/fixtures/node_path/src/index.js
  test/fixtures/typescript/src/App.test.ts
  test/fixtures/typescript/src/App.ts
  test/fixtures/typescript/src/absoluteLoad.ts
  test/fixtures/typescript/tsconfig.json
Labels: CLA Signed, tag: new feature

#6829 Upgrade to Lerna v3
  CONTRIBUTING.md
  package.json
  tasks/publish.sh
Labels: CLA Signed, tag: internal

#6840 Relax ESLint version range
  packages/babel-plugin-named-asset-import/package.json
  packages/babel-preset-react-app/package.json
  packages/confusing-browser-globals/package.json
  packages/create-react-app/package.json
  packages/eslint-config-react-app/package.json
  packages/react-app-polyfill/package.json
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
  packages/react-scripts/scripts/utils/verifyPackageTree.js
Labels: CLA Signed, tag: underlying tools

#6845 Change CRA version in `react-scripts` eject warning.
  packages/react-scripts/scripts/eject.js
Labels: CLA Signed, tag: enhancement

#6848 Remove no-watch flag in favor of watchAll=false
  docusaurus/docs/debugging-tests.md
  docusaurus/docs/running-tests.md
  packages/react-scripts/scripts/test.js
Labels: CLA Signed, tag: breaking change, tag: documentation

#6847 Add baseUrl documentation
  docusaurus/docs/importing-a-component.md
Labels: CLA Signed, tag: documentation

#6843 Update fsevents dependency version
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#6879 Update README.md
  packages/react-app-polyfill/README.md
Labels: CLA Signed, tag: documentation

#6862 Fix no-useless-constructor rule in TypeScript
  packages/eslint-config-react-app/index.js
Labels: CLA Signed, tag: bug fix

#6300 Remove body padding reset from templates
  packages/react-scripts/template-typescript/src/index.css
  packages/react-scripts/template/src/index.css
Labels: CLA Signed, tag: enhancement

#6881 Fix typo in deployment docs
  docusaurus/docs/deployment.md
Labels: CLA Signed, tag: documentation

#6810 Call to action button now "reacts" to being hovered :)
  docusaurus/website/static/css/custom.css
Labels: CLA Signed, tag: documentation

#6706 Generate SVG component name in Jest fileTransform
  packages/react-scripts/config/jest/fileTransform.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: enhancement

#6935 Grammar!
  docusaurus/docs/supported-browsers-features.md
Labels: tag: documentation

#6876 Change cssmodule classname hash to use repo relative paths instead of…
  packages/react-dev-utils/getCSSModuleLocalIdent.js
Labels: CLA Signed, tag: bug fix

#6887 Update dependencies babel preset with recent changes
  packages/babel-preset-react-app/dependencies.js
Labels: CLA Signed, tag: enhancement

#6854 Remove `Object.assign` from `MiniCssExtractPlugin` options
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: internal

#6898 Update GraphQL doc
  docusaurus/docs/loading-graphql-files.md
Labels: CLA Signed, tag: documentation
