Repository facebook/create-react-app, pull requests merged in 2019-06, with the labels that each got.

#7170 Update deprecated package reference
  docusaurus/docs/running-tests.md
Labels: CLA Signed, tag: documentation

#7179 Disabled Typescript no-undef rule per typescript-eslint #477
  packages/eslint-config-react-app/index.js
Labels: CLA Signed

#7208 Use correct babel transform for dynamic import in dependencies
  packages/babel-preset-react-app/dependencies.js
Labels: CLA Signed, tag: internal

#7219 fix: eslintrc overrides key should be an array, not object
  packages/eslint-config-react-app/index.js
Labels: CLA Signed, tag: bug fix

#7220 Disable Travis build
  .travis.yml
Labels: CLA Signed, tag: internal

#7222 Update @typescript-eslint package versions
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#6060 Add environment variable to control image inlining threshold
  docusaurus/docs/adding-images-fonts-and-files.md
  docusaurus/docs/advanced-configuration.md
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: new feature

#7262 Docs: replace the command line to install relay/macro
  docusaurus/docs/adding-relay.md
Labels: CLA Signed, tag: documentation

#7269 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/proposal.md
Labels: CLA Signed, issue: proposal, tag: internal

#7274 Update peer dependencies
  packages/eslint-config-react-app/README.md
Labels: CLA Signed, tag: documentation

#7257 Upgrade webpack to 4.35.0 to fix dynamic import issue
  packages/react-error-overlay/package.json
  packages/react-scripts/fixtures/kitchensink/src/App.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/DynamicImport.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/DynamicImport.test.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: bug fix

#7277 Handle browser arguments
  docusaurus/docs/advanced-configuration.md
  packages/react-dev-utils/openBrowser.js
Labels: CLA Signed

#7279 Documented --use-npm & --use-script
  docusaurus/docs/getting-started.md
Labels: CLA Signed
