Repository facebook/create-react-app, pull requests merged in 2019-08, with the labels that each got.

#7462 Added dependencies to bootstrap article when using custom SCSS.
  docusaurus/docs/adding-bootstrap.md
Labels: CLA Signed, tag: documentation

#7472 Typescript init: suggest `jsx: "react"` in tsconfig
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
Labels: CLA Signed, tag: enhancement

#5951 Set jsonpFunction by default
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: enhancement

#5829 Resolve relative paths for preprocessor styles
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: bug fix

#7480 Specify roots in Jest config
  packages/react-scripts/scripts/utils/createJestConfig.js
Labels: CLA Signed

#7482 100% lighthouse score for progressive web app
  packages/react-scripts/template-typescript/public/index.html
  packages/react-scripts/template-typescript/public/logo192.png
  packages/react-scripts/template-typescript/public/logo512.png
  packages/react-scripts/template-typescript/public/manifest.json
  packages/react-scripts/template-typescript/public/robots.txt
  packages/react-scripts/template/public/index.html
  packages/react-scripts/template/public/logo192.png
  packages/react-scripts/template/public/logo512.png
  packages/react-scripts/template/public/manifest.json
  packages/react-scripts/template/public/robots.txt
Labels: CLA Signed, tag: enhancement

#7248 Support comments in tsconfig.json
  packages/react-scripts/config/modules.js
Labels: CLA Signed

#7444 Fix for #6720: HMR not working in Firefox if proxy option present
  packages/react-dev-utils/WebpackDevServerUtils.js
Labels: CLA Signed, tag: bug fix

#7488 Adjusted deployment documentation for ZEIT Now
  docusaurus/docs/deployment.md
Labels: CLA Signed, tag: documentation

#7473 Bump dependencies
  package.json
  packages/babel-plugin-named-asset-import/package.json
  packages/babel-preset-react-app/package.json
  packages/confusing-browser-globals/package.json
  packages/create-react-app/package.json
  packages/react-app-polyfill/package.json
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/fixtures/kitchensink/.template.dependencies.json
  packages/react-scripts/fixtures/kitchensink/integration/config.test.js
  packages/react-scripts/fixtures/kitchensink/integration/initDOM.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/DynamicImport.test.js
  packages/react-scripts/package.json
  packages/react-scripts/template-typescript/public/index.html
  packages/react-scripts/template/public/index.html
Labels: CLA Signed, tag: underlying tools

#7080 Support configuring coveragePathIgnorePatterns
  packages/react-scripts/scripts/utils/createJestConfig.js
Labels: CLA Signed, tag: enhancement

#7176 Fix RegExp from navigateFallbackBlacklist (workbox)
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: enhancement

#6484 Fix launch.json for #5319
  docusaurus/docs/debugging-tests.md
Labels: CLA Signed

#7028 Add vscodium to the editor list
  packages/react-dev-utils/launchEditor.js
Labels: CLA Signed, tag: enhancement

#7496 bump sass-loader
  packages/react-scripts/package.json
Labels: CLA Signed, tag: enhancement

#7497 add readonly modifier for css module
  packages/react-scripts/lib/react-app.d.ts
Labels: CLA Signed, tag: enhancement

#5818 Remove unused dependencies in babel-preset-react-app
  packages/babel-preset-react-app/package.json
Labels: CLA Signed, tag: internal

#7500 Add links to Spectrum in README and docs
  README.md
  docusaurus/website/core/Footer.js
Labels: CLA Signed, tag: documentation

#7508 Don't block static files in robots.txt
  packages/react-scripts/template-typescript/public/robots.txt
  packages/react-scripts/template/public/robots.txt
Labels: CLA Signed

#7393 Ignore "jsx-a11y/aria-role" for React components
  packages/eslint-config-react-app/index.js
Labels: CLA Signed, tag: enhancement

#7499 Update docusaurus config
  docusaurus/website/siteConfig.js
Labels: CLA Signed

#7527 Update Netlify config
  docusaurus/website/i18n/en.json
  netlify.toml
Labels: CLA Signed, tag: documentation

#7513 Fix ESLint 6 support
  docusaurus/docs/setting-up-your-editor.md
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: bug fix

#7521 Show logo for mobile views in create-react-app.dev
  docusaurus/website/static/css/custom.css
Labels: CLA Signed, tag: documentation

#7536 add a migration step to remove static from robots.txt
  CHANGELOG.md
Labels: CLA Signed, tag: documentation

#7550 docs: update Flow documentation
  docusaurus/docs/adding-flow.md
Labels: CLA Signed

#7368 Correcting proxy sample
  docusaurus/docs/proxying-api-requests-in-development.md
Labels: CLA Signed, tag: documentation

#7585 remove trailing spaces
  packages/react-scripts/template-typescript/public/manifest.json
  packages/react-scripts/template/public/manifest.json
Labels: CLA Signed, tag: internal

#7613 Fix seams between changelog majors
  CHANGELOG-1.x.md
  CHANGELOG-2.x.md
Labels: CLA Signed
