Repository facebook/create-react-app, pull requests merged in 2019-03, with the labels that each got.

#6585 Revert "Speed up TypeScript v2 (#6406)"
  packages/react-dev-utils/ForkTsCheckerWebpackPlugin.js
  packages/react-dev-utils/README.md
  packages/react-dev-utils/WebpackDevServerUtils.js
  packages/react-dev-utils/package.json
  packages/react-dev-utils/typescriptFormatter.js
  packages/react-dev-utils/webpackHotDevClient.js
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
  packages/react-scripts/scripts/start.js
  test/fixtures/typescript-typecheck/.disable-pnp
  test/fixtures/typescript-typecheck/index.test.js
  test/fixtures/typescript-typecheck/package.json
  test/fixtures/typescript-typecheck/src/App.tsx
  test/fixtures/typescript-typecheck/src/index.tsx
Labels: CLA Signed, tag: internal

#6586 Reapply "Speed up TypeScript v2 (#6406)"
  packages/react-dev-utils/ForkTsCheckerWebpackPlugin.js
  packages/react-dev-utils/README.md
  packages/react-dev-utils/WebpackDevServerUtils.js
  packages/react-dev-utils/package.json
  packages/react-dev-utils/typescriptFormatter.js
  packages/react-dev-utils/webpackHotDevClient.js
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
  packages/react-scripts/scripts/start.js
  test/fixtures/typescript-typecheck/.disable-pnp
  test/fixtures/typescript-typecheck/index.test.js
  test/fixtures/typescript-typecheck/package.json
  test/fixtures/typescript-typecheck/src/App.tsx
  test/fixtures/typescript-typecheck/src/index.tsx
Labels: CLA Signed, tag: internal

#6386 [docs] revert removal of newlines from html
  docusaurus/docs/adding-custom-environment-variables.md
Labels: CLA Signed, tag: documentation

#6483 Update webpack-dev-server to 3.2.1
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#6502 Enable click to go to error in console part 2!
  packages/react-dev-utils/README.md
  packages/react-dev-utils/formatWebpackMessages.js
  packages/react-dev-utils/typescriptFormatter.js
Labels: CLA Signed, tag: enhancement

#6361 Updating html-webpack-plugin dep
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#6610 Convert JSON.stringify \n to os.EOL
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
Labels: CLA Signed, tag: bug fix

#6451 change class component to function component
  packages/react-scripts/template-typescript/src/App.tsx
  packages/react-scripts/template/src/App.js
Labels: CLA Signed, tag: enhancement

#6615 Allow .json type checking
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: breaking change, tag: enhancement

#6621 make compiler a const not a let
  packages/react-scripts/scripts/build.js
Labels: CLA Signed, tag: internal

#6614 Upgrade dependencies
  package.json
  packages/babel-preset-react-app/package.json
  packages/create-react-app/createReactApp.js
  packages/create-react-app/package.json
  packages/react-app-polyfill/package.json
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
  test/fixtures/__shared__/util/scripts.js
Labels: CLA Signed, tag: underlying tools

#5960 add command to add files to staging after eject
  packages/react-scripts/scripts/eject.js
  tasks/e2e-simple.sh
Labels: CLA Signed, tag: enhancement

#6625 change named import into default import
  packages/react-scripts/template-typescript/src/App.tsx
Labels: CLA Signed, tag: internal

#6374 Add note about npx caching and link to #6119
  docusaurus/docs/adding-typescript.md
Labels: CLA Signed, tag: documentation

#5686 Add empty mock for http2
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: enhancement

#6608 Support browserslist in @babel/preset-env
  docusaurus/docs/supported-browsers-features.md
  packages/babel-preset-react-app/create.js
  packages/react-dev-utils/browsersHelper.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: breaking change, tag: new feature

#5997 Support React Hooks (#5602)
  packages/babel-preset-react-app/create.js
  packages/eslint-config-react-app/README.md
  packages/eslint-config-react-app/index.js
  packages/eslint-config-react-app/package.json
  packages/react-scripts/package.json
Labels: CLA Signed

#6513 Add TypeScript linting support
  docusaurus/docs/setting-up-your-editor.md
  packages/eslint-config-react-app/index.js
  packages/eslint-config-react-app/package.json
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: breaking change, tag: new feature

#6278 Update to Jest 24
  package.json
  packages/babel-plugin-named-asset-import/package.json
  packages/confusing-browser-globals/package.json
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/fixtures/kitchensink/.template.dependencies.json
  packages/react-scripts/package.json
  packages/react-scripts/scripts/utils/createJestConfig.js
  tasks/e2e-installs.sh
  tasks/e2e-kitchensink-eject.sh
  tasks/e2e-kitchensink.sh
Labels: CLA Signed, tag: breaking change, tag: new feature

#6653 Unpin eslint-config-react-hooks dependency
  packages/eslint-config-react-app/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#5821 Add wait: false to options object for opn
  packages/react-dev-utils/openBrowser.js
Labels: CLA Signed, tag: enhancement

#6662 Sync version of babel-eslint in eslint-config-react-app for react-scripts V3
  packages/eslint-config-react-app/package.json
Labels: CLA Signed, tag: internal

#6674 Remove unused eslint comment
  packages/react-dev-utils/formatWebpackMessages.js
Labels: CLA Signed, tag: internal

#6669 Remove unnecessary shrink-to-fit=no meta data
  packages/react-scripts/template-typescript/public/index.html
  packages/react-scripts/template/public/index.html
Labels: CLA Signed, tag: enhancement

#6655 Change app component declaration from arrow function to regular function
  packages/react-scripts/template/src/App.js
Labels: CLA Signed, tag: internal

#6690 Remove duplicate url key in siteConfig
  docusaurus/website/siteConfig.js
Labels: CLA Signed

#6208 Add deployment instructions with AWS Amplify
  docusaurus/docs/deployment.md
Labels: CLA Signed, tag: documentation

#6700 Kill verdaccio in CI tasks cleanup
  tasks/e2e-behavior.sh
  tasks/e2e-installs.sh
  tasks/e2e-kitchensink-eject.sh
  tasks/e2e-kitchensink.sh
  tasks/e2e-simple.sh
Labels: CLA Signed, tag: internal

#6491 Update advanced-configuration.md
  docusaurus/docs/advanced-configuration.md
Labels: CLA Signed, tag: documentation

#6701 Remove project property from @typescript-eslint/parser options
  packages/eslint-config-react-app/index.js
Labels: CLA Signed, tag: underlying tools
