Repository facebook/create-react-app, pull requests merged in 2019-05, with the labels that each got.

#6945 Add clarifying note to TypeScript docs warning about global install of CRA
  docusaurus/docs/adding-typescript.md
Labels: CLA Signed, tag: documentation

#6856 Adds the configuration for PnP/Typescript
  packages/react-dev-utils/package.json
  packages/react-scripts/config/pnpTs.js
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: enhancement

#6937 Disable default-case lint rule for TypeScript
  packages/eslint-config-react-app/index.js
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
Labels: CLA Signed, tag: bug fix

#6979 Add note to restart the dev server after changing .env file
  docusaurus/docs/adding-custom-environment-variables.md
Labels: CLA Signed, tag: documentation

#7002 Temporary fix for babel-jest preflight error
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: bug fix

#6987 Disable no-dupe-class-members rule for TypeScript
  packages/eslint-config-react-app/index.js
Labels: CLA Signed, tag: bug fix

#7007 Unpin babel-jest
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: bug fix

#7016 Revert PR #6935 because CLA was not signed
  docusaurus/docs/supported-browsers-features.md
Labels: tag: documentation

#6055 Support for graceful extension of Jest config
  packages/react-scripts/scripts/utils/createJestConfig.js
Labels: CLA Signed

#7041 Updates the relay docs
  docusaurus/docs/adding-relay.md
Labels: CLA Signed, tag: documentation

#7039 docs: fix env-cmd example in deployment section
  docusaurus/docs/deployment.md
Labels: CLA Signed, tag: documentation

#7059 Correct spelling of browserslist
  docusaurus/docs/supported-browsers-features.md
Labels: CLA Signed, tag: documentation

#7079 Adjust typescript-eslint to not warn about typedefs when used before defined
  packages/eslint-config-react-app/index.js
Labels: CLA Signed, tag: bug fix

#7058 fix: Replaced opn (deprecated) with open
  packages/react-dev-utils/openBrowser.js
  packages/react-dev-utils/package.json
Labels: CLA Signed, tag: underlying tools

#6858 Add test to make sure .d.ts files are ignored when checking for TypeScript
  test/fixtures/issue-5947-not-typescript/index.test.js
Labels: CLA Signed, tag: internal

#7086 Improve breaking changes info for CRA 3.0.0
  CHANGELOG.md
Labels: CLA Signed, tag: documentation

#6877 Upgrade svgr to 4.2.0
  packages/react-scripts/package.json
Labels: CLA Signed, tag: internal

#6941 Fix compatibility of create-react-app to Node.js v0.10+
  packages/create-react-app/index.js
Labels: CLA Signed, tag: enhancement

#7096 Add Azure DevOps build pipeline
  README.md
  azure-pipelines-test-job.yml
  azure-pipelines.yml
  tasks/e2e-behavior.sh
  tasks/e2e-installs.sh
  tasks/e2e-kitchensink-eject.sh
  tasks/e2e-kitchensink.sh
  tasks/e2e-simple.sh
  tasks/local-registry.sh
  tasks/verdaccio.yaml
  test/fixtures/__shared__/util/scripts.js
  test/fixtures/__shared__/util/setup.js
  test/fixtures/mjs-support/__snapshots__/index.test.js.snap
  test/fixtures/mjs-support/index.test.js
  test/fixtures/mjs-support/package.json
  test/fixtures/mjs-support/src/App.js
  test/fixtures/webpack-message-formatting/index.test.js
Labels: CLA Signed, tag: internal

#7131 Update fsevents dependency version
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#7133 Make the OOM abreviation more clear
  docusaurus/docs/advanced-configuration.md
Labels: CLA Signed, tag: documentation
