Repository facebook/create-react-app, pull requests merged in 2019-02, with the labels that each got.

#6285 Allow react-scripts test --no-watch
  packages/react-scripts/scripts/test.js
Labels: CLA Signed, issue: proposal, tag: enhancement

#6080 Validation for multiple arguments if specified for create-react-app
  packages/create-react-app/createReactApp.js
Labels: CLA Signed

#6331 Update docs to document `--no-watch`
  docusaurus/docs/debugging-tests.md
  docusaurus/docs/getting-started.md
  docusaurus/docs/running-tests.md
Labels: CLA Signed, tag: documentation

#6292 Add Node DNS module to empty mocks
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed

#6342 fix local yarn create-react-app for local testing before publish
  tasks/cra.js
Labels: CLA Signed

#6346 Minor issue in README.md
  README.md
Labels: CLA Signed

#6355 Make manifest.json description more generic
  packages/react-scripts/template-typescript/public/index.html
  packages/react-scripts/template/public/index.html
Labels: CLA Signed, tag: documentation

#5903 Speed up TypeScript projects
  packages/react-dev-utils/WebpackDevServerUtils.js
  packages/react-dev-utils/typescriptFormatter.js
  packages/react-dev-utils/webpackHotDevClient.js
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
  packages/react-scripts/scripts/start.js
  test/fixtures/typescript-typecheck/.disable-pnp
  test/fixtures/typescript-typecheck/index.test.js
  test/fixtures/typescript-typecheck/package.json
  test/fixtures/typescript-typecheck/src/App.tsx
  test/fixtures/typescript-typecheck/src/index.tsx
Labels: CLA Signed, tag: enhancement

#6359 Update ZEIT Now deployment instructions
  docusaurus/docs/deployment.md
Labels: CLA Signed, tag: documentation

#5713 Sass source map for dev
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: enhancement

#6364 Use semicolons in the ProcessEnv interface
  packages/react-scripts/lib/react-app.d.ts
Labels: CLA Signed, tag: bug fix

#6307 Update babel-plugin-macros 2.4.4 -> 2.4.5
  packages/babel-preset-react-app/package.json
Labels: CLA Signed, tag: underlying tools

#6062 [docs] Warn/clarify that env vars are NOT "SECRET"
  docusaurus/docs/adding-custom-environment-variables.md
Labels: CLA Signed, tag: documentation

#5213 Add Jest typeahead plugin
  packages/react-scripts/package.json
  packages/react-scripts/scripts/utils/createJestConfig.js
Labels: CLA Signed, tag: enhancement

#6383 Update docs links to prefer HTTPS for supported domains
  docusaurus/docs/adding-bootstrap.md
  docusaurus/docs/advanced-configuration.md
  docusaurus/docs/alternatives-to-ejecting.md
  docusaurus/docs/code-splitting.md
  docusaurus/docs/deployment.md
  docusaurus/docs/developing-components-in-isolation.md
  docusaurus/docs/importing-a-component.md
  docusaurus/docs/making-a-progressive-web-app.md
  docusaurus/docs/proxying-api-requests-in-development.md
  docusaurus/docs/running-tests.md
  docusaurus/docs/troubleshooting.md
  docusaurus/docs/using-the-public-folder.md
Labels: CLA Signed, tag: documentation

#6393 Upgrade dependencies
  packages/babel-preset-react-app/package.json
  packages/react-app-polyfill/package.json
  packages/react-dev-utils/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#6395 Move fork-ts-checker-webpack-plugin dependency to react-dev-utils
  packages/react-dev-utils/ForkTsCheckerWebpackPlugin.js
  packages/react-dev-utils/package.json
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: bug fix

#5767 Add information for usage custom registries on e2e testing #4488
  CONTRIBUTING.md
Labels: CLA Signed, tag: documentation

#6365 Upgrade Docusaurus and enable new features
  docusaurus/website/package.json
  docusaurus/website/siteConfig.js
  docusaurus/website/yarn.lock
Labels: CLA Signed, tag: underlying tools

#5457 Add forward ref to React SVG Component
  packages/react-scripts/config/jest/fileTransform.js
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/SvgComponent.js
  packages/react-scripts/fixtures/kitchensink/src/features/webpack/SvgComponent.test.js
Labels: tag: enhancement

#6435 Allow for the ability to use `.d.ts` files without buying into typescript setup
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
Labels: CLA Signed

#6444 Revert "Switch to eval-source-map (#5060)"
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: bug fix

#6253 Only use `yarn.lock.cached` if using the default Yarn registry
  packages/create-react-app/createReactApp.js
Labels: CLA Signed

#6454 Fix typo in doc
  docusaurus/docs/running-tests.md
Labels: CLA Signed, tag: documentation

#6406 Speed up TypeScript v2
  packages/react-dev-utils/ForkTsCheckerWebpackPlugin.js
  packages/react-dev-utils/README.md
  packages/react-dev-utils/WebpackDevServerUtils.js
  packages/react-dev-utils/package.json
  packages/react-dev-utils/typescriptFormatter.js
  packages/react-dev-utils/webpackHotDevClient.js
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
  packages/react-scripts/scripts/start.js
  test/fixtures/typescript-typecheck/.disable-pnp
  test/fixtures/typescript-typecheck/index.test.js
  test/fixtures/typescript-typecheck/package.json
  test/fixtures/typescript-typecheck/src/App.tsx
  test/fixtures/typescript-typecheck/src/index.tsx
Labels: CLA Signed, tag: enhancement

#6472 revert css sourcemaps in development
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: bug fix

#6474 Remove latest Node version from Travis config
  .travis.yml
Labels: CLA Signed, tag: internal

#6387 Use contenthash instead of chunkhash for better long-term caching
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: underlying tools

#6438 Analyse also dependencies bundle
  docusaurus/docs/analyzing-the-bundle-size.md
Labels: CLA Signed, tag: documentation

#6482 minor typo fix in openBrowser
  packages/react-dev-utils/openBrowser.js
Labels: CLA Signed

#6481 Fix a typo
  packages/create-react-app/createReactApp.js
Labels: CLA Signed

#6419 Improved language used in markdown code blocks.
  CHANGELOG-0.x.md
  CHANGELOG-1.x.md
  CHANGELOG.md
  CONTRIBUTING.md
  docusaurus/docs/adding-a-sass-stylesheet.md
  docusaurus/docs/adding-custom-environment-variables.md
  docusaurus/docs/adding-typescript.md
  docusaurus/docs/analyzing-the-bundle-size.md
  docusaurus/docs/debugging-tests.md
  docusaurus/docs/deployment.md
  docusaurus/docs/proxying-api-requests-in-development.md
  docusaurus/docs/running-tests.md
  docusaurus/docs/using-https-in-development.md
  packages/babel-preset-react-app/README.md
  packages/confusing-browser-globals/README.md
  packages/react-app-polyfill/README.md
Labels: CLA Signed, tag: documentation

#6254 removed redundant statements
  packages/babel-preset-react-app/README.md
Labels: CLA Signed, tag: documentation

#6493 Remove AppVeyor config files
  appveyor.cleanup-cache.txt
  appveyor.yml
Labels: CLA Signed, tag: internal

#6511 Fix deployInstruction: Alt+click link appends comma at end
  packages/react-dev-utils/printHostingInstructions.js
Labels: tag: bug fix
