Repository facebook/create-react-app, pull requests merged in 2019-10, with the labels that each got.

#7754 Fix linting error when using rest props
  packages/react-scripts/package.json
Labels: CLA Signed, tag: bug fix

#6931 Adds TSC_COMPILE_ON_ERROR env var...
  docusaurus/docs/adding-typescript.md
  docusaurus/docs/advanced-configuration.md
  packages/react-dev-utils/README.md
  packages/react-dev-utils/WebpackDevServerUtils.js
  packages/react-scripts/scripts/build.js
  packages/react-scripts/scripts/start.js
Labels: CLA Signed, tag: new feature

#7729 Remove switch case
  packages/react-scripts/bin/react-scripts.js
Labels: CLA Signed, tag: underlying tools

#7302 docs: note that 2 to 3 migration may require deletion of node_modules
  CHANGELOG.md
Labels: CLA Signed, tag: documentation

#6980 Stop hiding the column number of ESLint errors
  packages/react-dev-utils/formatWebpackMessages.js
  test/fixtures/webpack-message-formatting/__snapshots__/index.test.js.snap
Labels: CLA Signed, tag: enhancement

#7755 Support setting baseUrl to root directory
  packages/react-scripts/config/modules.js
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/scripts/utils/createJestConfig.js
Labels: CLA Signed, tag: enhancement

#7687 Use installing package manager in README
  packages/react-scripts/scripts/init.js
Labels: CLA Signed, tag: enhancement

#7737 Support production profiling with React Developer Tools
  docusaurus/docs/available-scripts.md
  docusaurus/docs/production-build.md
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: new feature

#7773 Temporarily disable Windows in CI
  azure-pipelines-test-job.yml
  azure-pipelines.yml
  packages/create-react-app/createReactApp.js
  packages/react-dev-utils/InlineChunkHtmlPlugin.js
  packages/react-scripts/scripts/build.js
Labels: CLA Signed, tag: internal

#7726 Add babel runtime version to transform-runtime plugin to reduce bundle size
  packages/babel-preset-react-app/create.js
Labels: CLA Signed, tag: enhancement

#7022 Fix node_modules sourcemap config (which will fix VSCode debugging of CRA apps)
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: enhancement

#7796 Fixed process type in TypeScript template.
  packages/react-scripts/template-typescript/src/serviceWorker.ts
Labels: CLA Signed

#7764 Allow for browserslist environment variables
  packages/react-dev-utils/browsersHelper.js
Labels: CLA Signed

#7813 Clarify dynamic import stage in docs
  docusaurus/docs/supported-browsers-features.md
Labels: CLA Signed, tag: documentation

#7815 Tightens up the TypeScript docs
  docusaurus/docs/adding-typescript.md
Labels: CLA Signed, tag: documentation

#7821 Document how to use the .env file to enforce HTTPS
  docusaurus/docs/using-https-in-development.md
Labels: CLA Signed

#7822 Fix absolute paths issue in Jest
  packages/react-scripts/config/modules.js
Labels: CLA Signed, tag: bug fix

#7823 Document correct default behavior for HOST var
  docusaurus/docs/advanced-configuration.md
Labels: CLA Signed, tag: documentation

#7824 Fix grammar error in troubleshooting.md
  docusaurus/docs/troubleshooting.md
Labels: CLA Signed, tag: documentation

#7785 Upgrade to docusaurus 2
  docusaurus/docs/adding-bootstrap.md
  docusaurus/docs/adding-custom-environment-variables.md
  docusaurus/docs/adding-images-fonts-and-files.md
  docusaurus/docs/can-i-use-decorators.md
  docusaurus/docs/deployment.md
  docusaurus/docs/getting-started.md
  docusaurus/docs/importing-a-component.md
  docusaurus/docs/post-processing-css.md
  docusaurus/docs/proxying-api-requests-in-development.md
  docusaurus/docs/running-tests.md
  docusaurus/docs/setting-up-your-editor.md
  docusaurus/docs/troubleshooting.md
  docusaurus/website/.gitignore
  docusaurus/website/README.md
  docusaurus/website/core/Footer.js
  docusaurus/website/docusaurus.config.js
  docusaurus/website/i18n/en.json
  docusaurus/website/package.json
  docusaurus/website/pages/en/index.js
  docusaurus/website/siteConfig.js
  docusaurus/website/src/css/custom.css
  docusaurus/website/src/pages/index.js
  docusaurus/website/src/pages/styles.module.css
  docusaurus/website/static/CNAME
  docusaurus/website/static/css/custom.css
  docusaurus/website/yarn.lock
  netlify.toml
Labels: CLA Signed, tag: documentation

#7830 Revert logo in templates
  packages/react-scripts/template-typescript/public/favicon.ico
  packages/react-scripts/template-typescript/public/logo192.png
  packages/react-scripts/template-typescript/public/logo512.png
  packages/react-scripts/template-typescript/src/App.css
  packages/react-scripts/template-typescript/src/logo.svg
  packages/react-scripts/template/public/favicon.ico
  packages/react-scripts/template/public/logo192.png
  packages/react-scripts/template/public/logo512.png
  packages/react-scripts/template/src/App.css
  packages/react-scripts/template/src/logo.svg
Labels: CLA Signed, tag: internal

#7832 feat: add additional Jest keys to whitelist
  docusaurus/docs/running-tests.md
  packages/react-scripts/scripts/utils/createJestConfig.js
Labels: CLA Signed, tag: enhancement

#7686 Link to React documentation for code splitting
  docusaurus/docs/code-splitting.md
Labels: CLA Signed, tag: documentation

#7809 Add a note about .eslintignore files being respected
  docusaurus/docs/setting-up-your-editor.md
Labels: CLA Signed, tag: documentation

#7839 added check for typescript template and unsupported node version
  packages/create-react-app/createReactApp.js
Labels: CLA Signed, tag: bug fix

#7841 Update getting-started.md
  docusaurus/docs/getting-started.md
Labels: CLA Signed, tag: documentation

#7840 Link to ASP.NET Core docs
  docusaurus/docs/integrating-with-an-api-backend.md
Labels: CLA Signed, tag: documentation

#7849 chore: update README.md gif links
  README.md
  docusaurus/docs/getting-started.md
Labels: CLA Signed, tag: documentation

#7853 Update adding-bootstrap.md
  docusaurus/docs/adding-bootstrap.md
Labels: CLA Signed

#7856 Move unused eslint webpack import into @remove-on-eject block
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: underlying tools

#7819 📖 DOC: Improvement
  README.md
Labels: CLA Signed, tag: documentation

#7857 feat: upgrade terser & enable parallel minification in wsl
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: internal

#7861 Add a GitHub Action that runs the build script
  .github/workflows/build.yml
Labels: CLA Signed, tag: internal

#6449 Edit InterpolateHtmlPlugin hook (#6448)
  packages/react-dev-utils/InterpolateHtmlPlugin.js
Labels: CLA Signed, tag: bug fix

#7474 Fix notations of loopback addresses
  packages/react-scripts/template-typescript/src/serviceWorker.ts
  packages/react-scripts/template/src/serviceWorker.js
Labels: CLA Signed, tag: documentation

#6753 Add Service-Worker header to checkValidServiceWorker
  packages/react-scripts/template-typescript/src/serviceWorker.ts
  packages/react-scripts/template/src/serviceWorker.js
Labels: CLA Signed, tag: enhancement

#6352 Add additional information for postcss errors (#6282)
  packages/react-scripts/scripts/build.js
Labels: CLA Signed, tag: enhancement

#7870 Fix eslint complaints in build.js
  packages/react-scripts/scripts/build.js
Labels: CLA Signed, tag: underlying tools

#7852 Add Alex to lint documentation
  .alexignore
  .alexrc
  .github/workflows/lint.yml
  CONTRIBUTING.md
  README.md
  docusaurus/docs/adding-custom-environment-variables.md
  docusaurus/docs/adding-images-fonts-and-files.md
  docusaurus/docs/adding-relay.md
  docusaurus/docs/alternatives-to-ejecting.md
  docusaurus/docs/can-i-use-decorators.md
  docusaurus/docs/debugging-tests.md
  docusaurus/docs/deployment.md
  docusaurus/docs/developing-components-in-isolation.md
  docusaurus/docs/fetching-data-with-ajax-requests.md
  docusaurus/docs/getting-started.md
  docusaurus/docs/installing-a-dependency.md
  docusaurus/docs/making-a-progressive-web-app.md
  docusaurus/docs/running-tests.md
  docusaurus/docs/setting-up-your-editor.md
  docusaurus/docs/supported-browsers-features.md
  docusaurus/docs/title-and-meta-tags.md
  docusaurus/docs/using-global-variables.md
  docusaurus/docs/using-the-public-folder.md
  package.json
  packages/react-scripts/fixtures/kitchensink/README.md
Labels: CLA Signed, tag: documentation

#7874 Bump docusaurus 🦖
  docusaurus/website/package.json
  docusaurus/website/src/pages/index.js
  docusaurus/website/yarn.lock
Labels: CLA Signed, tag: documentation

#7876 Bump styling related loaders
  packages/create-react-app/yarn.lock.cached
  packages/react-dev-utils/README.md
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#7878 Remove alex precommit check
  package.json
Labels: CLA Signed, tag: internal

#7880 Pass through fully specified template name
  packages/create-react-app/createReactApp.js
Labels: CLA Signed, tag: internal

#7814 Upgrade outdated packages
  packages/babel-plugin-named-asset-import/package.json
  packages/babel-preset-react-app/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#7882 refactor: remove double coerce
  packages/create-react-app/createReactApp.js
Labels: CLA Signed, tag: internal

#7789 Add yarn.lock to .gitignore
  .gitignore
Labels: CLA Signed, tag: internal

#7897 chore: Fix broken link for CRA deployment
  packages/react-dev-utils/printHostingInstructions.js
Labels: CLA Signed

#7896 chore: Fix broken link for e2e README
  CONTRIBUTING.md
Labels: CLA Signed, tag: underlying tools

#7881 Add @testing-library to the default templates
  package.json
  packages/cra-template-typescript/template.json
  packages/cra-template-typescript/template/src/App.test.tsx
  packages/cra-template-typescript/template/src/setupTests.ts
  packages/cra-template/template.json
  packages/cra-template/template/src/App.test.js
  packages/cra-template/template/src/setupTests.js
  tasks/e2e-installs.sh
Labels: CLA Signed, tag: enhancement

#7817 Add numeric separator support
  packages/babel-preset-react-app/create.js
  packages/babel-preset-react-app/package.json
  packages/react-dev-utils/browsersHelper.js
Labels: CLA Signed, tag: new feature

#7910 Update open
  packages/react-dev-utils/openBrowser.js
  packages/react-dev-utils/package.json
Labels: CLA Signed, tag: underlying tools

#7860 Mark TypeScript as an optional peer dependency for react-scripts
  packages/react-scripts/package.json
Labels: CLA Signed, tag: bug fix
