Repository facebook/create-react-app, pull requests merged in 2019-12, with the labels that each got.

#8079 webpackHotDevClient now uses wss when https is used
  packages/react-dev-utils/webpackHotDevClient.js
Labels: CLA Signed, tag: bug fix

#8077 Add custom-templates to docs sidebar
  docusaurus/website/sidebars.json
Labels: CLA Signed, tag: documentation

#8080 Fix typo in CHANGELOG.md
  CHANGELOG.md
Labels: CLA Signed, tag: documentation

#7803 Remove error for @typescript-eslint/no-namespace
  packages/eslint-config-react-app/index.js
  test/fixtures/typescript/src/App.ts
Labels: CLA Signed, tag: enhancement

#8122 Fix CI build
  packages/babel-preset-react-app/package.json
  packages/create-react-app/yarn.lock.cached
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
  tasks/e2e-simple.sh
Labels: CLA Signed, tag: underlying tools

#8106 Fix CSS font-face minification
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: bug fix

#8116 Add slashes to WebSocket protocol URL
  packages/react-dev-utils/webpackHotDevClient.js
Labels: CLA Signed, tag: bug fix

#8124 Fix typo in comment: `?.` is right, `.?` is not
  packages/babel-preset-react-app/create.js
Labels: CLA Signed, tag: documentation

#8111 chore: update docusaurus & tweak site
  docusaurus/docs/getting-started.md
  docusaurus/website/docusaurus.config.js
  docusaurus/website/package.json
  docusaurus/website/src/css/custom.css
  docusaurus/website/yarn.lock
Labels: CLA Signed, tag: documentation

#8102 [Security] Update terser webpack plugin
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#8168 Add current version and bin location to --info output
  packages/create-react-app/createReactApp.js
Labels: CLA Signed, tag: enhancement

#8163 Bump pkgUp
  packages/react-dev-utils/browsersHelper.js
  packages/react-dev-utils/package.json
Labels: CLA Signed, tag: underlying tools

#8164 Bump chalk
  packages/create-react-app/package.json
  packages/react-dev-utils/README.md
  packages/react-dev-utils/package.json
  packages/react-dev-utils/typescriptFormatter.js
  packages/react-error-overlay/package.json
Labels: CLA Signed, tag: underlying tools

#8176 Bump internal dependencies
  docusaurus/website/package.json
  packages/create-react-app/package.json
  packages/react-app-polyfill/package.json
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#8132 Add package-runner note to readme
  README.md
Labels: CLA Signed, tag: documentation

#8147 update PWA docs links to point to template package
  docusaurus/docs/making-a-progressive-web-app.md
Labels: CLA Signed, tag: documentation

#8178 Minor refactors in create-react-app
  packages/create-react-app/createReactApp.js
Labels: CLA Signed, tag: internal

#8028 fix(react-scripts): proactively append to .gitignore during generation
  packages/react-scripts/scripts/init.js
Labels: CLA Signed

#8171 Bump babel-plugin-tester and fix breaking changes
  packages/babel-plugin-named-asset-import/index.test.js
  packages/babel-plugin-named-asset-import/package.json
Labels: CLA Signed, tag: underlying tools

#8212 Little typo
  docusaurus/docs/supported-browsers-features.md
Labels: CLA Signed, tag: documentation

#8194 Replace favicon in templates
  packages/cra-template-typescript/template/public/favicon.ico
  packages/cra-template/template/public/favicon.ico
Labels: CLA Signed, tag: enhancement
