Repository facebook/create-react-app, pull requests merged in 2020-08, with the labels that each got.

#9241 Updated README.md Templates to Follow ESLint Markdown Rules
  packages/cra-template-typescript/template/README.md
  packages/cra-template/template/README.md
Labels: CLA Signed, tag: documentation

#9245 [Doc] fix React Testing Library example
  docusaurus/docs/running-tests.md
Labels: CLA Signed, tag: documentation

#9380 Update running-tests.md
  docusaurus/docs/running-tests.md
Labels: CLA Signed, tag: documentation

#9350 Add Fast Refresh warning when using React < 16.10
  docusaurus/docs/advanced-configuration.md
  packages/react-dev-utils/webpackHotDevClient.js
  packages/react-scripts/config/env.js
  packages/react-scripts/scripts/start.js
Labels: CLA Signed, tag: enhancement

#9390 Publish refreshOverlayInterop with react-dev-utils
  packages/react-dev-utils/package.json
Labels: CLA Signed, tag: bug fix

#9401 fix: remove deprecated rule
  packages/eslint-config-react-app/README.md
  packages/eslint-config-react-app/index.js
Labels: CLA Signed, tag: breaking change

#9059 clean formatMessage usage
  packages/react-dev-utils/formatWebpackMessages.js
Labels: CLA Signed, tag: internal

#9252 feat: Update testing-library dependencies to latest
  package.json
  packages/cra-template-typescript/template.json
  packages/cra-template/template.json
Labels: CLA Signed, tag: internal

#9374 fix: use default modules option from `preset-env`
  packages/babel-preset-react-app/create.js
  packages/babel-preset-react-app/dependencies.js
Labels: CLA Signed, tag: bug fix

#8933 Bump immer version
  packages/react-dev-utils/package.json
Labels: CLA Signed, tag: underlying tools

#9392 Upgrade whatwg-fetch
  packages/react-app-polyfill/package.json
Labels: CLA Signed, tag: underlying tools

#9412 Fix template name handling
  packages/create-react-app/__tests__/.eslintrc
  packages/create-react-app/__tests__/getTemplateInstallPackage.test.js
  packages/create-react-app/createReactApp.js
  packages/create-react-app/index.js
  packages/create-react-app/package.json
Labels: CLA Signed, tag: bug fix

#9461 chore: update to jest@26.3
  package.json
  packages/babel-plugin-named-asset-import/package.json
  packages/confusing-browser-globals/package.json
  packages/cra-template-typescript/template.json
  packages/create-react-app/package.json
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/fixtures/kitchensink/template.json
  packages/react-scripts/package.json
Labels: CLA Signed

#9471 Fixes in the /packages/react-devs-utils/README.md file
  packages/react-dev-utils/README.md
Labels: CLA Signed, tag: documentation

#9363 Added CRA logo in README.md
  README.md
Labels: CLA Signed

#9560 Update Vercel deployment documentation
  docusaurus/docs/deployment.md
Labels: CLA Signed, tag: documentation
