Repository facebook/create-react-app, pull requests merged in 2020-04, with the labels that each got.

#8768 Add .cjs and .mjs files support to test runner
  packages/react-scripts/scripts/utils/createJestConfig.js
Labels: CLA Signed, tag: bug fix

#8763 Use simplified import of @testing-library/jest-dom
  docusaurus/docs/running-tests.md
Labels: CLA Signed, tag: documentation

#5847 Include absoluteRuntime in babel preset docs
  packages/babel-preset-react-app/README.md
Labels: CLA Signed, tag: documentation

#8749 Specify what files are served form a bare local copy
  CONTRIBUTING.md
Labels: CLA Signed, tag: internal

#8734 fix: handle templates without main package field
  packages/cra-template-typescript/package.json
  packages/cra-template/package.json
  packages/react-scripts/scripts/init.js
Labels: tag: bug fix

#8582 Add experimental react-refresh support
  docusaurus/docs/advanced-configuration.md
  packages/react-dev-utils/webpackHotDevClient.js
  packages/react-scripts/config/env.js
  packages/react-scripts/config/hotRefreshOverlayModuleStub.js
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: new feature

#8791 Add setupTests.js to the list of generated files
  README.md
Labels: CLA Signed, tag: documentation

#8684 Simplify wording in setting-up-your-editor.md
  docusaurus/docs/setting-up-your-editor.md
Labels: CLA Signed, tag: documentation

#8610 Update url to see prettier in action
  docusaurus/docs/setting-up-your-editor.md
Labels: tag: documentation

#8834 Don't use webpack multi entry unnecessarily
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: enhancement

#8892 Widen eslint-config-react-app peer dependency versions
  packages/eslint-config-react-app/package.json
Labels: CLA Signed

#8925 Revert "Replace favicon in templates"
  packages/cra-template-typescript/template/public/favicon.ico
  packages/cra-template/template/public/favicon.ico
Labels: CLA Signed
