Repository facebook/create-react-app, pull requests merged in 2020-07, with the labels that each got.

#9244 Explain how to uninstall create-react-app globally
  README.md
  docusaurus/docs/adding-typescript.md
  docusaurus/docs/getting-started.md
  packages/react-scripts/scripts/init.js
Labels: CLA Signed, tag: documentation

#9317 Upgrade dependencies
  package.json
  packages/babel-plugin-named-asset-import/package.json
  packages/babel-preset-react-app/package.json
  packages/confusing-browser-globals/package.json
  packages/create-react-app/package.json
  packages/create-react-app/yarn.lock.cached
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/fixtures/kitchensink/template.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#9205 Switch to the Workbox InjectManifest plugin
  docusaurus/docs/making-a-progressive-web-app.md
  packages/cra-template-typescript/template/src/index.tsx
  packages/cra-template-typescript/template/src/serviceWorkerRegistration.ts
  packages/cra-template/template/src/index.js
  packages/cra-template/template/src/serviceWorkerRegistration.js
  packages/react-scripts/config/paths.js
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: breaking change, tag: new feature

#9348 Upgrade refresh plugin
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#9251 feat: Update ESLint dependencies
  package.json
  packages/eslint-config-react-app/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#9349 Remove server worker registration from default templates
  packages/cra-template-typescript/template/src/index.tsx
  packages/cra-template-typescript/template/src/serviceWorkerRegistration.ts
  packages/cra-template/template/src/index.js
  packages/cra-template/template/src/serviceWorkerRegistration.js
Labels: CLA Signed

#9231 Clarify wording in adding TypeScript to existing project
  docusaurus/docs/adding-typescript.md
Labels: CLA Signed, tag: documentation

#9375 feat: better refresh plugin integration
  packages/react-dev-utils/refreshOverlayInterop.js
  packages/react-error-overlay/src/index.js
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: enhancement

#9359 feat: exit on outdated create-react-app version
  packages/create-react-app/createReactApp.js
Labels: CLA Signed, tag: breaking change, tag: new feature
