Repository facebook/create-react-app, pull requests merged in 2020-06, with the labels that each got.

#8955 Upgrade to Jest 26
  package.json
  packages/babel-plugin-named-asset-import/package.json
  packages/confusing-browser-globals/package.json
  packages/create-react-app/yarn.lock.cached
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/fixtures/kitchensink/template.json
  packages/react-scripts/package.json
  packages/react-scripts/scripts/utils/createJestConfig.js
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
  test/fixtures/jsconfig/src/App.js
Labels: CLA Signed, tag: breaking change, tag: underlying tools

#9114 Allow testMatch for jest config
  packages/react-scripts/scripts/utils/createJestConfig.js
Labels: CLA Signed, tag: new feature

#7937 Support scss absolute path resolution for url()
  packages/react-scripts/config/webpack.config.js
  test/fixtures/global-scss-asset-resolution/.disable-pnp
  test/fixtures/global-scss-asset-resolution/index.test.js
  test/fixtures/global-scss-asset-resolution/package.json
  test/fixtures/global-scss-asset-resolution/src/images/logo.svg
  test/fixtures/global-scss-asset-resolution/src/index.js
  test/fixtures/global-scss-asset-resolution/src/index.scss
Labels: CLA Signed

#9132 Upgrade dependencies
  package.json
  packages/babel-preset-react-app/package.json
  packages/cra-template-typescript/template.json
  packages/cra-template/template.json
  packages/create-react-app/package.json
  packages/create-react-app/yarn.lock.cached
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#9116 Add performance relayer + documentation (web-vitals)
  docusaurus/docs/measuring-performance.md
  docusaurus/website/sidebars.json
  package.json
  packages/cra-template-typescript/template.json
  packages/cra-template-typescript/template/src/index.tsx
  packages/cra-template-typescript/template/src/reportWebVitals.ts
  packages/cra-template/template.json
  packages/cra-template/template/src/index.js
  packages/cra-template/template/src/reportWebVitals.js
  tasks/e2e-installs.sh
Labels: CLA Signed, tag: enhancement

#9042 Update deployment docs for Azure Static Web Apps
  docusaurus/docs/deployment.md
Labels: CLA Signed, tag: documentation

#9102 Replace Spectrum links with GitHub Discussions
  README.md
  docusaurus/website/docusaurus.config.js
Labels: CLA Signed, tag: internal

#8694 Use process.execPath to spawn node subprocess
  packages/react-dev-utils/openBrowser.js
  packages/react-scripts/bin/react-scripts.js
Labels: CLA Signed, tag: bug fix

#9196 Upgrade dependencies
  package.json
  packages/babel-preset-react-app/package.json
  packages/cra-template-typescript/template.json
  packages/cra-template/template.json
  packages/create-react-app/package.json
  packages/create-react-app/yarn.lock.cached
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
  test/fixtures/typescript-advanced/package.json
  test/fixtures/typescript-typecheck/package.json
  test/fixtures/typescript/package.json
Labels: CLA Signed, tag: underlying tools

#7787 Bump version of Verdaccio
  azure-pipelines-test-job.yml
  azure-pipelines.yml
  docusaurus/docs/deployment.md
  docusaurus/docs/measuring-performance.md
  packages/cra-template/template/src/reportWebVitals.js
  tasks/local-registry.sh
  tasks/verdaccio.yaml
Labels: CLA Signed, tag: internal

#8978 Support ESLint 7.x
  package.json
  packages/eslint-config-react-app/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: breaking change, tag: underlying tools

#8895 Fix chai URL
  docusaurus/docs/running-tests.md
Labels: CLA Signed, tag: documentation
