Repository facebook/create-react-app, pull requests merged in 2020-12, with the labels that each got.

#10198 remove chalk from formatWebpackMessages
  packages/react-dev-utils/formatWebpackMessages.js
Labels: CLA Signed, tag: underlying tools

#10213 Upgrade @svgr/webpack to fix build error
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#9569 Improve vendor chunk names in development
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: enhancement

#10003 Update postcss packages
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#10091 Recovered some integration tests
  packages/react-dev-utils/package.json
  packages/react-error-overlay/src/__tests__/extract-source-map.js
  packages/react-error-overlay/src/__tests__/get-source-map.js
  packages/react-error-overlay/src/__tests__/parser/generic.js
  packages/react-scripts/config/jest/babelTransform.js
  packages/react-scripts/fixtures/kitchensink/template.json
  packages/react-scripts/fixtures/kitchensink/template/integration/webpack.test.js
  packages/react-scripts/scripts/utils/createJestConfig.js
Labels: CLA Signed, tag: internal

#9988 Upgrade sass-loader
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#9977 Move ESLint cache file into node_modules
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: enhancement

#10216 Revert "Update postcss packages"
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#10214 Remove references to Node 8
  README.md
  docusaurus/docs/debugging-tests.md
Labels: CLA Signed, tag: documentation
