Repository facebook/create-react-app, pull requests merged in 2020-09, with the labels that each got.

#9618 Fix insensitive language in Docusaurus docs
  docusaurus/docs/making-a-progressive-web-app.md
Labels: CLA Signed

#9587 Remove EXTEND_ESLINT and add Jest rules
  docusaurus/docs/advanced-configuration.md
  docusaurus/docs/setting-up-your-editor.md
  packages/cra-template-typescript/template.json
  packages/cra-template/template.json
  packages/eslint-config-react-app/README.md
  packages/eslint-config-react-app/index.js
  packages/eslint-config-react-app/jest.js
  packages/eslint-config-react-app/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: breaking change

#9258 fix: Fix azure-pipelines' endOfLine
  .gitattributes
  .github/stale.yml
  azure-pipelines-test-job.yml
  azure-pipelines.yml
  package.json
Labels: CLA Signed, tag: internal

#9526 Update template dependencies to latest version
  packages/cra-template-typescript/template.json
  packages/cra-template/template.json
Labels: CLA Signed, tag: underlying tools

#9073 Update running-tests.md
  docusaurus/docs/running-tests.md
Labels: CLA Signed, tag: documentation

#9434 feat: Update ESLint dependencies
  package.json
  packages/eslint-config-react-app/README.md
  packages/eslint-config-react-app/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#9630 Emphasise that Next.js is capable of SSG
  README.md
Labels: CLA Signed, tag: documentation

#9499 fix: add alt tag to improve accessibility of docusaurus website
  docusaurus/website/src/pages/index.js
Labels: CLA Signed

#9640 fix: resolve CI build failure
  packages/eslint-config-react-app/README.md
  packages/eslint-config-react-app/base.js
  packages/eslint-config-react-app/index.js
  packages/eslint-config-react-app/package.json
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed

#9645 Use new JSX transform with React 17
  packages/babel-preset-react-app/create.js
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: enhancement

#9639 Upgrade dependencies
  package.json
  packages/babel-plugin-named-asset-import/package.json
  packages/babel-preset-react-app/package.json
  packages/confusing-browser-globals/package.json
  packages/cra-template-typescript/template.json
  packages/cra-template/template.json
  packages/create-react-app/package.json
  packages/create-react-app/yarn.lock.cached
  packages/eslint-config-react-app/index.js
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/fixtures/kitchensink/template.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#9683 fix: resolve ESLint config from appPath
  packages/eslint-config-react-app/base.js
  packages/eslint-config-react-app/index.js
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: bug fix
