Repository facebook/create-react-app, pull requests merged in 2020-02, with the labels that each got.

#7259 feat(react-scripts): allow PUBLIC_URL in develoment mode
  docusaurus/docs/advanced-configuration.md
  packages/react-dev-utils/README.md
  packages/react-dev-utils/WebpackDevServerUtils.js
  packages/react-dev-utils/__tests__/getPublicUrlOrPath.test.js
  packages/react-dev-utils/getPublicUrlOrPath.js
  packages/react-dev-utils/noopServiceWorkerMiddleware.js
  packages/react-dev-utils/package.json
  packages/react-dev-utils/redirectServedPathMiddleware.js
  packages/react-scripts/config/paths.js
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/config/webpackDevServer.config.js
  packages/react-scripts/package.json
  packages/react-scripts/scripts/build.js
  packages/react-scripts/scripts/start.js
Labels: CLA Signed, issue: proposal, tag: enhancement

#8412 Change arrow functions to function declarations
  docusaurus/docs/adding-images-fonts-and-files.md
  packages/cra-template-typescript/template/src/App.tsx
Labels: CLA Signed, tag: enhancement

#8437 Fix navbar line break in header
  docusaurus/website/src/css/custom.css
Labels: CLA Signed, tag: documentation

#8292 Fixes unchecked access to 'deploy' script on build
  packages/react-dev-utils/printHostingInstructions.js
Labels: CLA Signed, tag: bug fix

#8439 Downgrade chalk for ie 11 support
  packages/create-react-app/yarn.lock.cached
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
Labels: CLA Signed, tag: bug fix

#8442 fix(react-scripts): do not redirect served path if request may proxy
  packages/react-dev-utils/README.md
  packages/react-dev-utils/WebpackDevServerUtils.js
  packages/react-scripts/config/webpackDevServer.config.js
  packages/react-scripts/scripts/start.js
Labels: CLA Signed, tag: enhancement

#8450 fix(typescriptFormatter): use chalk@2 constructor
  packages/react-dev-utils/typescriptFormatter.js
Labels: issue: bug

#8459 update open to v7.0.2
  packages/react-dev-utils/openBrowser.js
  packages/react-dev-utils/package.json
Labels: CLA Signed, tag: underlying tools

#8475 Correct webpack name casing
  CHANGELOG-0.x.md
  CHANGELOG-1.x.md
  CHANGELOG-2.x.md
  README.md
  docusaurus/docs/adding-a-stylesheet.md
  docusaurus/docs/adding-images-fonts-and-files.md
  docusaurus/docs/available-scripts.md
  docusaurus/docs/folder-structure.md
  docusaurus/docs/getting-started.md
  docusaurus/docs/importing-a-component.md
  docusaurus/docs/troubleshooting.md
  docusaurus/docs/using-the-public-folder.md
  docusaurus/website/src/pages/index.js
  packages/cra-template-typescript/template/README.md
  packages/cra-template/template/README.md
  packages/react-dev-utils/InterpolateHtmlPlugin.js
  packages/react-dev-utils/README.md
  packages/react-dev-utils/WatchMissingNodeModulesPlugin.js
  packages/react-dev-utils/WebpackDevServerUtils.js
  packages/react-dev-utils/formatWebpackMessages.js
  packages/react-dev-utils/package.json
  packages/react-dev-utils/webpackHotDevClient.js
  packages/react-error-overlay/src/utils/getPrettyURL.js
  packages/react-scripts/config/env.js
  packages/react-scripts/config/paths.js
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/config/webpackDevServer.config.js
  packages/react-scripts/fixtures/kitchensink/template/integration/webpack.test.js
Labels: CLA Signed, tag: documentation

#8378 Downgrade style-loader to v0.23.1 due to CSS modules hot reload not working with v1.0.0 and above
  packages/react-scripts/package.json
Labels: CLA Signed

#8509 Bumps pnp-webpack-plugin
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#7203 Closes webpack dev server and exits process on "end" stdin
  packages/react-scripts/scripts/start.js
Labels: CLA Signed, tag: bug fix

#7790 Widen eslint-config-react-app peer dependency versions
  README.md
  docusaurus/docs/integrating-with-an-api-backend.md
  docusaurus/docs/using-https-in-development.md
  packages/cra-template/template/src/serviceWorker.js
  packages/eslint-config-react-app/README.md
  packages/eslint-config-react-app/package.json
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/ArrayDestructuring.js
Labels: CLA Signed, tag: bug fix

#8526 Fix optional chaining and nullish coalescing support
  packages/babel-preset-react-app/create.js
  packages/babel-preset-react-app/package.json
Labels: CLA Signed, tag: bug fix

#8561 Indicate that the file structure is the template's
  docusaurus/docs/custom-templates.md
Labels: CLA Signed

#8539 allow specification of package.main in template.json
  packages/react-scripts/scripts/init.js
Labels: CLA Signed, tag: enhancement
