Repository facebook/create-react-app, pull requests merged in 2020-05, with the labels that each got.

#8947 Minor/patch dependency upgrades
  package.json
  packages/babel-preset-react-app/package.json
  packages/create-react-app/package.json
  packages/create-react-app/yarn.lock.cached
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#8362 Upgrade to Jest 25
  CHANGELOG-0.x.md
  package.json
  packages/babel-plugin-named-asset-import/package.json
  packages/babel-preset-react-app/README.md
  packages/confusing-browser-globals/package.json
  packages/cra-template-typescript/template.json
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/fixtures/kitchensink/template.json
  packages/react-scripts/package.json
  packages/react-scripts/scripts/utils/createJestConfig.js
Labels: CLA Signed, tag: underlying tools

#8948 Drop Node 8 support
  azure-pipelines-test-job.yml
  azure-pipelines.yml
  docusaurus/docs/getting-started.md
  package.json
  packages/cra-template-typescript/package.json
  packages/cra-template/package.json
  packages/create-react-app/createReactApp.js
  packages/create-react-app/index.js
  packages/create-react-app/package.json
  packages/react-app-polyfill/package.json
  packages/react-dev-utils/package.json
  packages/react-scripts/fixtures/kitchensink/template.json
  packages/react-scripts/package.json
  tasks/e2e-old-node.sh
  tasks/e2e-typescript-unsupported-node.sh
  tasks/local-test.sh
  test/fixtures/webpack-message-formatting/__snapshots__/index.test.js.snap
  test/fixtures/webpack-message-formatting/index.test.js
Labels: CLA Signed, tag: breaking change

#8939 Bump React Hooks ESLint plugin to 4.0.0
  packages/eslint-config-react-app/package.json
  packages/react-scripts/package.json
Labels: tag: breaking change, tag: underlying tools

#8651 Update build script deployment URL
  packages/react-dev-utils/printHostingInstructions.js
Labels: CLA Signed, tag: documentation

#8845 Do not check for interactive session to shut down dev server
  packages/react-scripts/scripts/start.js
Labels: CLA Signed, tag: bug fix

#8638 Support source maps for scss in dev environments
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: enhancement

#8700 Skip stdin resuming to support lerna parallel
  packages/react-scripts/scripts/start.js
Labels: CLA Signed, tag: bug fix

#7899 Set resetMocks to true by default in jest config
  packages/react-scripts/scripts/utils/createJestConfig.js
Labels: CLA Signed, tag: breaking change

#8926 Add import/no-anonymous-default-export lint rule
  packages/eslint-config-react-app/index.js
  packages/react-scripts/fixtures/kitchensink/template/src/absoluteLoad.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/config/BaseUrl.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/env/ExpandEnvVariables.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/env/FileEnvVariables.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/env/PublicUrl.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/env/ShellEnvVariables.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/ArrayDestructuring.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/ArraySpread.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/AsyncAwait.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/ClassProperties.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/ComputedProperties.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/CustomInterpolation.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/DefaultParameters.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/DestructuringAndAwait.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/Generators.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/NullishCoalescing.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/ObjectDestructuring.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/ObjectSpread.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/OptionalChaining.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/Promises.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/RestAndDefault.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/RestParameters.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/syntax/TemplateInterpolation.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/webpack/CssInclusion.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/webpack/CssModulesInclusion.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/webpack/DynamicImport.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/webpack/ImageInclusion.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/webpack/JsonInclusion.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/webpack/LinkedModules.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/webpack/NoExtInclusion.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/webpack/SassInclusion.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/webpack/SassModulesInclusion.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/webpack/ScssInclusion.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/webpack/ScssModulesInclusion.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/webpack/SvgComponent.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/webpack/SvgInCss.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/webpack/SvgInclusion.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/webpack/UnknownExtInclusion.js
  test/fixtures/node_path/src/App.js
  test/fixtures/node_path/src/absoluteLoad.js
Labels: CLA Signed, tag: breaking change

#8891 Bump style-loader to 1.2.1
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#8838 Support devDependencies in templates
  docusaurus/docs/custom-templates.md
  packages/react-scripts/scripts/init.js
Labels: CLA Signed, tag: documentation, tag: new feature

#8952 fix react-refresh babel plugin not applied
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: internal

#8246 Add a VSCode tip in the CSS reset section
  docusaurus/docs/adding-css-reset.md
Labels: CLA Signed, tag: documentation

#8790 Add back in --stats output from webpack.
  packages/react-scripts/package.json
  packages/react-scripts/scripts/build.js
Labels: CLA Signed, tag: new feature

#8460 Fix --use-pnp for Yarn 2
  packages/create-react-app/createReactApp.js
Labels: CLA Signed, tag: enhancement

#8492 Replace period in CSS Module classnames
  packages/react-dev-utils/__tests__/getCSSModuleLocalIdent.test.js
  packages/react-dev-utils/getCSSModuleLocalIdent.js
Labels: CLA Signed, tag: bug fix

#8957 Move shortlinks to cra.link
  docusaurus/docs/making-a-progressive-web-app.md
  packages/cra-template-typescript/template/src/index.tsx
  packages/cra-template-typescript/template/src/serviceWorker.ts
  packages/cra-template/template/src/index.js
  packages/cra-template/template/src/serviceWorker.js
  packages/react-dev-utils/printBuildError.js
  packages/react-dev-utils/printHostingInstructions.js
  packages/react-scripts/scripts/init.js
  packages/react-scripts/scripts/start.js
  packages/react-scripts/template/README.md
Labels: CLA Signed, tag: documentation

#8858 Remove outdated comment
  packages/babel-preset-react-app/create.js
Labels: CLA Signed, tag: internal

#8975 bump webpack-dev-server to 3.11.0
  packages/react-scripts/package.json
Labels: CLA Signed

#8950 Dependency major version upgrades
  .prettierrc
  docusaurus/docs/adding-css-reset.md
  package.json
  packages/babel-plugin-named-asset-import/index.js
  packages/babel-preset-react-app/create.js
  packages/babel-preset-react-app/dependencies.js
  packages/babel-preset-react-app/dev.js
  packages/babel-preset-react-app/index.js
  packages/babel-preset-react-app/prod.js
  packages/babel-preset-react-app/test.js
  packages/babel-preset-react-app/webpack-overrides.js
  packages/create-react-app/createReactApp.js
  packages/create-react-app/package.json
  packages/create-react-app/yarn.lock.cached
  packages/react-app-polyfill/stable.js
  packages/react-dev-utils/ForkTsCheckerWebpackPlugin.js
  packages/react-dev-utils/WebpackDevServerUtils.js
  packages/react-dev-utils/formatWebpackMessages.js
  packages/react-dev-utils/launchEditor.js
  packages/react-dev-utils/package.json
  packages/react-dev-utils/typescriptFormatter.js
  packages/react-dev-utils/webpackHotDevClient.js
  packages/react-error-overlay/build.js
  packages/react-error-overlay/package.json
  packages/react-error-overlay/src/containers/StackFrameCodeBlock.js
  packages/react-error-overlay/src/effects/proxyConsole.js
  packages/react-error-overlay/src/index.js
  packages/react-error-overlay/src/utils/parser.js
  packages/react-scripts/config/hotRefreshOverlayModuleStub.js
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/config/webpackDevServer.config.js
  packages/react-scripts/fixtures/kitchensink/template/src/subfolder/lol.js
  packages/react-scripts/package.json
  packages/react-scripts/scripts/init.js
  packages/react-scripts/scripts/start.js
  test/fixtures/node_path/src/App.js
Labels: CLA Signed, tag: breaking change, tag: underlying tools

#9081 Update packages
  packages/babel-preset-react-app/package.json
  packages/create-react-app/package.json
  packages/create-react-app/yarn.lock.cached
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#9037 Fix dotenv file loading order
  docusaurus/docs/adding-custom-environment-variables.md
  packages/react-scripts/config/env.js
  packages/react-scripts/fixtures/kitchensink/template/integration/env.test.js
Labels: CLA Signed, tag: breaking change, tag: bug fix

#8934 feat: remove typescript flag and NODE_PATH support
  docusaurus/docs/advanced-configuration.md
  packages/create-react-app/createReactApp.js
  packages/react-scripts/config/modules.js
  packages/react-scripts/scripts/build.js
  packages/react-scripts/scripts/init.js
  packages/react-scripts/scripts/start.js
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
  tasks/e2e-installs.sh
  test/fixtures/jsconfig/.disable-pnp
  test/fixtures/jsconfig/index.test.js
  test/fixtures/jsconfig/jsconfig.json
  test/fixtures/jsconfig/package.json
  test/fixtures/jsconfig/src/App.js
  test/fixtures/jsconfig/src/App.test.js
  test/fixtures/jsconfig/src/absoluteLoad.js
  test/fixtures/jsconfig/src/index.js
  test/fixtures/node_path/.env
Labels: CLA Signed, tag: breaking change

#9089 Update getting-started.md
  docusaurus/docs/getting-started.md
Labels: CLA Signed
