Repository facebook/create-react-app, pull requests merged in 2020-01, with the labels that each got.

#8298 Support shorthand scoped templates
  docusaurus/docs/custom-templates.md
  packages/create-react-app/createReactApp.js
Labels: CLA Signed

#8219 Add template support for any package.json keys (#8082)
  docusaurus/docs/custom-templates.md
  packages/cra-template-typescript/template.json
  packages/cra-template/template.json
  packages/react-scripts/fixtures/kitchensink/template.json
  packages/react-scripts/scripts/init.js
Labels: CLA Signed, tag: enhancement

#8293 Minor grammatical edit
  docusaurus/docs/supported-browsers-features.md
Labels: CLA Signed, tag: documentation

#8324 Update Dependencies
  packages/babel-preset-react-app/package.json
  packages/create-react-app/package.json
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#8177 Remove React.FC from Typescript template
  packages/cra-template-typescript/template/src/App.tsx
Labels: CLA Signed, tag: enhancement

#8364 Downgrade open from 7.0.0 to 6.4.0
  packages/react-dev-utils/openBrowser.js
  packages/react-dev-utils/package.json
Labels: CLA Signed, tag: underlying tools

#8353 Remove outdated babel plugins
  package.json
  packages/babel-preset-react-app/create.js
  packages/babel-preset-react-app/dependencies.js
  packages/babel-preset-react-app/package.json
  packages/create-react-app/package.json
  packages/create-react-app/yarn.lock.cached
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
  tasks/local-test.sh
Labels: CLA Signed, tag: underlying tools

#8099 Add titleProp to SVGR ReactComponent type definition
  packages/react-scripts/lib/react-app.d.ts
Labels: CLA Signed, tag: bug fix

#8120 Sync dependencies babel config
  packages/babel-preset-react-app/dependencies.js
Labels: CLA Signed, tag: bug fix

#8092 Update custom template docs with instructions for testing custom template locally
  docusaurus/docs/custom-templates.md
Labels: CLA Signed, tag: documentation

#8247 Update setting-up-your-editor.md
  docusaurus/docs/setting-up-your-editor.md
Labels: CLA Signed, tag: documentation

#8307 Remove outdated docs regarding vscode eslint extension and typescript autofix
  docusaurus/docs/setting-up-your-editor.md
Labels: CLA Signed, tag: documentation

#8281 Fix sass importLoaders
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: bug fix

#8255 Add "Disallow:" to robots.txt
  packages/cra-template/template/public/robots.txt
Labels: CLA Signed, tag: bug fix

#6548 Add helpful message to the footer
  packages/react-error-overlay/src/containers/RuntimeErrorContainer.js
Labels: CLA Signed, tag: enhancement

#8394 Update docs according to lint-staged v10
  docusaurus/docs/setting-up-your-editor.md
Labels: CLA Signed, tag: documentation

#8380 docs: Add troubleshooting documentation on ENOSPC
  docusaurus/docs/troubleshooting.md
Labels: CLA Signed, tag: documentation

#8379 Make the PWA link point to the right place
  packages/react-scripts/template/README.md
Labels: CLA Signed

#8377 Update commit message to use imperative mood
  packages/react-scripts/scripts/init.js
Labels: CLA Signed

#8367 Wider Chromium support for openBrowser
  packages/react-dev-utils/openBrowser.js
  packages/react-dev-utils/openChrome.applescript
Labels: CLA Signed, tag: underlying tools

#8402 fix(test): force install npm in e2e-behaviour
  tasks/e2e-behavior.sh
Labels: CLA Signed, tag: underlying tools

#8390 setupTestFrameworkScriptFile is deprecated
  docusaurus/docs/running-tests.md
Labels: CLA Signed, tag: documentation

#8403 Fix robots.txt for TS
  packages/cra-template-typescript/template/public/robots.txt
Labels: CLA Signed, tag: bug fix

#8299 Update public folder usage docs to clarify globals
  docusaurus/docs/using-the-public-folder.md
Labels: CLA Signed, tag: documentation

#8282 Run git init before template dependencies are installed
  packages/react-scripts/scripts/init.js
Labels: CLA Signed, tag: underlying tools

#7948 Support JetBrains Rider IDE as an editor
  packages/react-dev-utils/launchEditor.js
Labels: CLA Signed, tag: underlying tools

#7750 Enable custom sockjs pathname for hot reloading server.
  docusaurus/docs/advanced-configuration.md
  packages/react-dev-utils/WebpackDevServerUtils.js
  packages/react-dev-utils/webpackHotDevClient.js
  packages/react-scripts/config/env.js
  packages/react-scripts/config/webpackDevServer.config.js
Labels: CLA Signed, tag: enhancement

#5845 Add option to provide custom ssl certificates during development
  docusaurus/docs/using-https-in-development.md
  packages/react-scripts/config/getHttpsConfig.js
  packages/react-scripts/config/webpackDevServer.config.js
Labels: CLA Signed, issue: proposal, tag: enhancement

#8272 Handle service worker error in Firefox
  packages/cra-template-typescript/template/src/serviceWorker.ts
  packages/cra-template/template/src/serviceWorker.js
Labels: CLA Signed, tag: bug fix, tag: enhancement
