Repository facebook/create-react-app, pull requests merged in 2020-03, with the labels that each got.

#8276 Use native ESLint behaviour when extending
  docusaurus/docs/advanced-configuration.md
  docusaurus/docs/setting-up-your-editor.md
  packages/react-scripts/config/webpack.config.js
Labels: tag: bug fix, tag: documentation

#8515 Fix proxying API request docs
  docusaurus/docs/proxying-api-requests-in-development.md
Labels: CLA Signed, tag: documentation

#8620 Bump dependencies
  azure-pipelines.yml
  packages/babel-preset-react-app/package.json
  packages/create-react-app/yarn.lock.cached
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: internal

#8558 Add React.StrictMode to default templates
  packages/cra-template-typescript/template/src/index.tsx
  packages/cra-template/template/src/index.js
Labels: CLA Signed, tag: enhancement

#8681 Update to Babel 7.9
  packages/babel-preset-react-app/package.json
  packages/create-react-app/yarn.lock.cached
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#8705 Update template tests
  packages/cra-template-typescript/template/src/App.test.tsx
  packages/cra-template/template/src/App.test.js
Labels: CLA Signed, tag: enhancement

#8713 Bump typescript template to 3.8
  packages/cra-template-typescript/template.json
Labels: CLA Signed
