Repository facebook/create-react-app, pull requests merged in 2020-10, with the labels that each got.

#9611 Add AVIF image support
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/lib/react-app.d.ts
Labels: CLA Signed, tag: new feature

#9788 fix: resolve new JSX transform issues
  packages/babel-preset-react-app/create.js
  packages/eslint-config-react-app/base.js
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed

#9728 Upgrade Docusaurus to latest version
  docusaurus/docs/deployment.md
  docusaurus/website/docusaurus.config.js
  docusaurus/website/package.json
  docusaurus/website/src/pages/index.js
  docusaurus/website/yarn.lock
Labels: CLA Signed, tag: documentation

#9751 Replace deprecated eslint-loader by eslint-webpack-plugin
  packages/eslint-config-react-app/base.js
  packages/react-dev-utils/eslintFormatter.js
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed

#9841 Bump resolve-url-loader version
  packages/react-scripts/package.json
Labels: CLA Signed

#9805 Fix refreshOverlayInterop module scope error
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed

#9670 fix(eslint-config-react-app): Make eslint-plugin-jest an optional peerDependency
  packages/eslint-config-react-app/README.md
  packages/eslint-config-react-app/package.json
Labels: CLA Signed

#8963 feat(eslint-config-react-app): Add jest & testing-library rules
  packages/eslint-config-react-app/README.md
  packages/eslint-config-react-app/jest.js
  packages/eslint-config-react-app/package.json
  packages/react-error-overlay/.eslintrc
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: breaking change, tag: new feature

#9856 feat: Update ESLint dependencies
  package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#9853 feat: remove unused React imports
  packages/cra-template/template/src/App.js
  packages/cra-template/template/src/App.test.js
Labels: CLA Signed, tag: enhancement

#9857 feat: Update all dependencies
  package.json
  packages/babel-plugin-named-asset-import/package.json
  packages/babel-preset-react-app/package.json
  packages/confusing-browser-globals/package.json
  packages/cra-template-typescript/template.json
  packages/cra-template/template.json
  packages/create-react-app/package.json
  packages/eslint-config-react-app/package.json
  packages/react-app-polyfill/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#9861 New JSX Transform opt out
  docusaurus/docs/advanced-configuration.md
  packages/babel-preset-react-app/create.js
  packages/eslint-config-react-app/base.js
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: enhancement

#9734 Use new JSX setting with TypeScript 4.1.0
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
Labels: tag: enhancement

#9863 Upgrade to React 17
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed

#9865 Pass JSX runtime setting to Babel preset in Jest config
  packages/react-scripts/config/jest/babelTransform.js
Labels: CLA Signed

#9864 Add link to Open Collective
  README.md
Labels: CLA Signed

#9911 fix: slow recompile time
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: bug fix

#9860 chore: Update .prettierrc
  .prettierrc
Labels: CLA Signed, tag: internal

#9516 [ImgBot] Optimize images
  docusaurus/website/static/img/docusaurus.svg
  docusaurus/website/static/img/logo-og.png
  docusaurus/website/static/img/logo.svg
  docusaurus/website/static/img/update.png
  packages/cra-template-typescript/template/src/logo.svg
  packages/cra-template/template/src/logo.svg
  packages/react-scripts/fixtures/kitchensink/template/src/features/webpack/assets/logo.svg
  packages/react-scripts/fixtures/kitchensink/template/src/features/webpack/assets/tiniest-cat.jpg
  screencast.svg
  test/fixtures/relative-paths/src/logo.svg
Labels: CLA Signed, tag: internal

#9884 fix: page doesn't get refreshed when FAST_REFRESH=false
  packages/react-dev-utils/webpackHotDevClient.js
Labels: CLA Signed, tag: bug fix

#9885 fix: `React is not defined` compilation error after ejected
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: bug fix

#9869 Fix react-jsx error
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
Labels: CLA Signed, tag: bug fix

#9921 Fix noFallthroughCasesInSwitch/jsx object is not extensible
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
Labels: CLA Signed, tag: bug fix
