Repository facebook/create-react-app, pull requests merged in 2020-11, with the labels that each got.

#10040 Remove trailing space in reportWebVitals.ts
  packages/cra-template-typescript/template/src/reportWebVitals.ts
Labels: CLA Signed, tag: bug fix

#10052 docs: add React Testing Library as a library requiring jsdom
  docusaurus/docs/running-tests.md
Labels: CLA Signed

#10048 Increase Workbox's maximumFileSizeToCacheInBytes
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: enhancement

#10083 replace inquirer with prompts
  packages/create-react-app/createReactApp.js
  packages/create-react-app/package.json
  packages/react-dev-utils/WebpackDevServerUtils.js
  packages/react-dev-utils/browsersHelper.js
  packages/react-dev-utils/inquirer.js
  packages/react-dev-utils/package.json
  packages/react-scripts/package.json
  packages/react-scripts/scripts/eject.js
Labels: CLA Signed, tag: internal

#10143 chore: bump web-vital dependency version
  package.json
  packages/cra-template-typescript/template.json
  packages/cra-template/template.json
Labels: CLA Signed, tag: underlying tools

#10141 chore: bump typescript version
  packages/cra-template-typescript/template.json
Labels: CLA Signed, tag: underlying tools

#9964 Add TypeScript 4.x as peerDependency to react-scripts
  packages/react-scripts/package.json
Labels: CLA Signed, tag: bug fix
