Repository facebook/create-react-app, pull requests merged in 2021-11, with the labels that each got.

#11597 Update package.json
  package-lock.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: internal

#11619 The default port used by `serve` has changed
  docusaurus/docs/deployment.md
Labels: CLA Signed, tag: documentation

#11646 Update webpack and dev server
  package-lock.json
  packages/react-scripts/package.json
Labels: CLA Signed
