Repository facebook/create-react-app, pull requests merged in 2021-02, with the labels that each got.

#9473 docs: add missing override options for Jest config
  docusaurus/docs/running-tests.md
Labels: CLA Signed, tag: documentation

#10217 Fix CI tests
  packages/create-react-app/yarn.lock.cached
  tasks/e2e-simple.sh
Labels: CLA Signed, tag: internal

#10027 appTsConfig immutability handling by immer
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
Labels: CLA Signed, tag: internal

#8986 Add support for new BUILD_PATH advanced configuration variable
  docusaurus/docs/advanced-configuration.md
  packages/react-scripts/config/paths.js
Labels: CLA Signed, tag: new feature

#10170 Add opt-out for eslint-webpack-plugin
  docusaurus/docs/advanced-configuration.md
  packages/react-dev-utils/eslintFormatter.js
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: enhancement

#10384 tests: update test case to match the description
  packages/create-react-app/__tests__/getTemplateInstallPackage.test.js
Labels: CLA Signed, tag: internal

#10312 Bump webpack-dev-server 3.11.0 -> 3.11.1
  packages/react-scripts/package.json
Labels: CLA Signed

#10590 Upgrade eslint-webpack-plugin to fix opt-out flag
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: bug fix

#10412 update immer to 8.0.1 to address vulnerability
  packages/react-dev-utils/package.json
Labels: CLA Signed, tag: internal
