Repository facebook/create-react-app, pull requests merged in 2021-12, with the labels that each got.

#11375 feat(eslint-config-react-app): support ESLint 8.x
  package-lock.json
  package.json
  packages/eslint-config-react-app/README.md
  packages/eslint-config-react-app/jest.js
  packages/eslint-config-react-app/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: enhancement

#11624 Update all dependencies
  package-lock.json
  package.json
  packages/babel-plugin-named-asset-import/package.json
  packages/babel-preset-react-app/package.json
  packages/confusing-browser-globals/package.json
  packages/create-react-app/package.json
  packages/create-react-app/yarn.lock.cached
  packages/react-app-polyfill/package.json
  packages/react-dev-utils/__tests__/getCSSModuleLocalIdent.test.js
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-error-overlay/src/utils/generateAnsiHTML.js
  packages/react-scripts/package.json
  test/integration/create-react-app/index.test.js
Labels: CLA Signed, tag: internal

#11706 Remove cached lockfile
  CONTRIBUTING.md
  package.json
  packages/create-react-app/createReactApp.js
  packages/create-react-app/package.json
  packages/create-react-app/yarn.lock.cached
  tasks/compile-lockfile.js
  tasks/publish.sh
  test/integration/create-react-app/index.test.js
Labels: CLA Signed, tag: internal

#11413 fix(webpackDevServer): disable overlay for warnings
  packages/react-scripts/config/webpackDevServer.config.js
Labels: CLA Signed, tag: bug fix

#11723 chore(test): make all tests install with `npm ci`
  .github/workflows/build.yml
  .github/workflows/integration.yml
  .github/workflows/lint.yml
  azure-pipelines-test-job.yml
  tasks/e2e-behavior.sh
  tasks/e2e-installs.sh
  tasks/e2e-kitchensink-eject.sh
  tasks/e2e-kitchensink.sh
  tasks/e2e-simple.sh
  tasks/local-test.sh
Labels: CLA Signed, tag: internal

#11717 Add support for Tailwind
  package-lock.json
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
  tasks/cra.js
Labels: CLA Signed, tag: enhancement
