Repository facebook/create-react-app, pull requests merged in 2021-04, with the labels that each got.

#10805 Update PWA docs to point at the cra-template-pwa package
  docusaurus/docs/making-a-progressive-web-app.md
Labels: CLA Signed, tag: documentation

#10511 Fix ICSS syntax in stylesheets
  packages/react-scripts/config/webpack.config.js
Labels: CLA Signed, tag: bug fix

#10288 Upgrade docs http links to https
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGELOG-0.x.md
  CHANGELOG-1.x.md
  docusaurus/docs/adding-css-reset.md
  docusaurus/docs/code-splitting.md
  docusaurus/docs/deployment.md
  docusaurus/docs/importing-a-component.md
  packages/babel-preset-react-app/README.md
  packages/eslint-config-react-app/README.md
Labels: CLA Signed, tag: documentation

#10779 Suggest sass instead of node-sass package
  docusaurus/docs/adding-a-sass-stylesheet.md
  docusaurus/docs/adding-bootstrap.md
  packages/react-dev-utils/formatWebpackMessages.js
  test/fixtures/webpack-message-formatting/index.test.js
Labels: CLA Signed, tag: documentation

#10784 Remove outdated comments on react-refresh
  packages/react-scripts/config/env.js
Labels: CLA Signed, tag: internal
