Repository facebook/create-react-app, pull requests merged in 2021-03, with the labels that each got.

#10631 Update IMAGE_INLINE_SIZE_LIMIT docs
  docusaurus/docs/advanced-configuration.md
Labels: CLA Signed, tag: documentation

#10644 Security Fix for Command Injection - huntr.dev
  packages/react-dev-utils/getProcessForPort.js
Labels: CLA Signed

#10456 Update PostCSS packages
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools

#10205 Update ModuleNotFoundPlugin to support Webpack 5
  packages/react-dev-utils/ModuleNotFoundPlugin.js
Labels: CLA Signed, tag: enhancement

#10763 Trivial English fixes
  packages/cra-template/template/README.md
Labels: CLA Signed, tag: documentation
