Repository facebook/create-react-app, pull requests merged in 2021-09, with the labels that each got.

#11304 Use npm v7 with workspaces for local development and testing
  .github/workflows/build.yml
  .github/workflows/integration.yml
  .github/workflows/lint.yml
  .gitignore
  CONTRIBUTING.md
  azure-pipelines-test-job.yml
  docusaurus/website/README.md
  docusaurus/website/yarn.lock
  netlify.toml
  package-lock.json
  package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/fixtures/kitchensink/template/README.md
  tasks/cra.js
  tasks/e2e-behavior.sh
  tasks/e2e-installs.sh
  tasks/e2e-kitchensink-eject.sh
  tasks/e2e-kitchensink.sh
  tasks/e2e-simple.sh
  tasks/publish.sh
  test/README.md
  test/fixtures/__shared__/util/scripts.js
  test/fixtures/__shared__/util/setup.js
  test/fixtures/boostrap-sass/.disable-pnp
  test/fixtures/global-scss-asset-resolution/.disable-pnp
  test/fixtures/jsconfig/.disable-pnp
  test/fixtures/typescript-advanced/.disable-pnp
  test/fixtures/typescript-typecheck/.disable-pnp
  test/fixtures/typescript/.disable-pnp
  test/fixtures/webpack-message-formatting/.disable-pnp
Labels: CLA Signed, tag: internal

#11322 Use env var to detect yarn or npm as the package manager
  azure-pipelines.yml
  docusaurus/docs/getting-started.md
  packages/create-react-app/createReactApp.js
  tasks/e2e-installs.sh
  tasks/e2e-kitchensink-eject.sh
  tasks/e2e-simple.sh
  test/integration/create-react-app/index.test.js
Labels: CLA Signed, tag: enhancement

#11294 fix: resolve dependency issues in v5 alpha
  package-lock.json
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed

#11338 Upgrade jest and related packages from 26.6.0 to 27.1.0
  package-lock.json
  package.json
  packages/babel-plugin-named-asset-import/package.json
  packages/confusing-browser-globals/package.json
  packages/create-react-app/package.json
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-error-overlay/src/__tests__/get-source-map.js
  packages/react-scripts/config/jest/babelTransform.js
  packages/react-scripts/fixtures/kitchensink/template.json
  packages/react-scripts/fixtures/kitchensink/template/jest.transform.js
  packages/react-scripts/package.json
  packages/react-scripts/scripts/utils/createJestConfig.js
Labels: CLA Signed, tag: underlying tools

#11325 allow CORS on webpack-dev-server
  packages/react-scripts/config/webpackDevServer.config.js
Labels: CLA Signed, tag: underlying tools

#11415 Bump template dependency version
  packages/confusing-browser-globals/README.md
  packages/cra-template-typescript/template.json
  packages/cra-template/template.json
  packages/create-react-app/createReactApp.js
  packages/create-react-app/index.js
Labels: CLA Signed, tag: internal
