Repository facebook/create-react-app, pull requests merged in 2021-07, with the labels that each got.

#11176 Run npm with --no-audit
  packages/create-react-app/createReactApp.js
  packages/react-scripts/scripts/init.js
Labels: CLA Signed, tag: enhancement

#11170 Wp5 update webpack dependencies and fix minor issues
  packages/babel-preset-react-app/create.js
  packages/babel-preset-react-app/package.json
  packages/react-dev-utils/README.md
  packages/react-dev-utils/WatchMissingNodeModulesPlugin.js
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/config/pnpTs.js
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/package.json
Labels: CLA Signed

#11188 Deprecate root level template.json keys
  package-lock.json
  packages/react-scripts/scripts/init.js
Labels: CLA Signed, tag: breaking change, tag: internal

#11105 fix: fast refresh stops on needed bail outs
  packages/react-dev-utils/webpackHotDevClient.js
Labels: CLA Signed, tag: enhancement

#10761 chore: migrate to @babel/eslint-parser
  packages/eslint-config-react-app/README.md
  packages/eslint-config-react-app/base.js
  packages/eslint-config-react-app/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
  packages/react-scripts/scripts/build.js
  packages/react-scripts/scripts/utils/verifyPackageTree.js
Labels: CLA Signed, tag: underlying tools

#11252 Remove package-lock.json
  package-lock.json
Labels: CLA Signed
