Repository facebook/create-react-app, pull requests merged in 2021-05, with the labels that each got.

#10317 eslint-config-react-app typo fix
  packages/eslint-config-react-app/README.md
Labels: CLA Signed, tag: documentation

#10907 Fix link address
  docusaurus/docs/using-the-public-folder.md
Labels: CLA Signed, tag: documentation

#10791 Bump immer version for fixing security issue
  packages/react-dev-utils/package.json
Labels: CLA Signed, tag: underlying tools

#10381 test(create-react-app): add integration tests
  .eslintrc.json
  .github/workflows/integration.yml
  package.json
  test/integration/create-react-app/index.test.js
Labels: CLA Signed

#10961 [WP5] Webpack5 update
  .eslintrc.json
  .github/workflows/integration.yml
  azure-pipelines-test-job.yml
  azure-pipelines.yml
  docusaurus/docs/advanced-configuration.md
  docusaurus/docs/using-the-public-folder.md
  package.json
  packages/create-react-app/__tests__/getTemplateInstallPackage.test.js
  packages/eslint-config-react-app/README.md
  packages/react-dev-utils/ModuleNotFoundPlugin.js
  packages/react-dev-utils/ModuleScopePlugin.js
  packages/react-dev-utils/README.md
  packages/react-dev-utils/WebpackDevServerUtils.js
  packages/react-dev-utils/evalSourceMapMiddleware.js
  packages/react-dev-utils/formatWebpackMessages.js
  packages/react-dev-utils/package.json
  packages/react-dev-utils/typescriptFormatter.js
  packages/react-dev-utils/webpackHotDevClient.js
  packages/react-error-overlay/package.json
  packages/react-error-overlay/webpack.config.js
  packages/react-scripts/config/paths.js
  packages/react-scripts/config/webpack.config.js
  packages/react-scripts/config/webpack/persistentCache/createEnvironmentHash.js
  packages/react-scripts/config/webpackDevServer.config.js
  packages/react-scripts/fixtures/kitchensink/template/integration/webpack.test.js
  packages/react-scripts/fixtures/kitchensink/template/src/features/webpack/JsonInclusion.js
  packages/react-scripts/package.json
  packages/react-scripts/scripts/eject.js
  packages/react-scripts/scripts/start.js
  packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js
  test/integration/create-react-app/index.test.js
Labels: CLA Signed

#10121 Add support for Webpack 5 message objects
  packages/react-dev-utils/formatWebpackMessages.js
Labels: CLA Signed

#10797 Unpin babel dependencies
  packages/babel-preset-react-app/package.json
  packages/react-dev-utils/package.json
  packages/react-error-overlay/package.json
  packages/react-scripts/package.json
Labels: CLA Signed, tag: underlying tools
