Repository facebook/create-react-app, pull requests merged in 2022-01, with the labels that each got.

#11757 prevent both npm and yarn commands from being copied
  docusaurus/docs/adding-typescript.md
Labels: CLA Signed, tag: documentation

#11805 docs: Changelog 5.0.0
  CHANGELOG-4.x.md
  CHANGELOG.md
Labels: CLA Signed, tag: documentation, tag: announcement

#11594 Fix a typo in deployment.md
  docusaurus/docs/deployment.md
Labels: CLA Signed, tag: documentation

#11622 updated deprecated rules
  packages/eslint-config-react-app/index.js
Labels: CLA Signed, tag: enhancement

#11640 Ensure posix compliant joins for urls in middleware
  packages/react-dev-utils/noopServiceWorkerMiddleware.js
  packages/react-dev-utils/redirectServedPathMiddleware.js
Labels: CLA Signed, tag: bug fix

#11985 Ignore docs when publishing
  docusaurus/website/package.json
Labels: CLA Signed, tag: internal
