Repository facebook/create-react-app, pull requests merged in 2022-06, with the labels that each got.

#12521 update a debugger for VS Code
  docusaurus/docs/setting-up-your-editor.md
Labels: CLA Signed

#12464 Update making-a-progressive-web-app.md
  docusaurus/docs/making-a-progressive-web-app.md
Labels: CLA Signed

#12337 Update getting-started.md
  docusaurus/docs/getting-started.md
Labels: CLA Signed

#12242 Update adding-a-router.md
  docusaurus/docs/adding-a-router.md
Labels: CLA Signed

#11837 Update links in `README`
  README.md
Labels: CLA Signed

#10696 Chore: Update document to GitHub default branch
  docusaurus/docs/deployment.md
Labels: CLA Signed, stale

#10543 Updated pace.js link
  docusaurus/docs/using-the-public-folder.md
Labels: stale

#11315 Chore: (Docs) Updates for the Storybook docs
  docusaurus/docs/developing-components-in-isolation.md
Labels: CLA Signed

#10501 docs: Make hyperlink consistent
  docusaurus/docs/pre-rendering-into-static-html-files.md
Labels: CLA Signed, stale

#12080 docs: update jest links
  docusaurus/docs/running-tests.md
Labels: CLA Signed
